/// Service-managed CTAS pins (S3 Tables create-first flow, `ServiceManagedLocation`).
use super::super::*;
use super::common::*;
use std::future::Future;
use std::pin::Pin;
use std::sync::Mutex;
use std::sync::atomic::{AtomicUsize, Ordering};

type BoxedCatalogFuture<'a, T> = Pin<Box<dyn Future<Output = iceberg::Result<T>> + Send + 'a>>;

#[derive(Debug, Clone, Copy)]
enum CommitInjection {
    None,
    UpdateTable(iceberg::ErrorKind),
    PublishCreate(iceberg::ErrorKind),
}

/// Mirrors the fork's service-assigned location contract and can fail at commit time.
#[derive(Debug)]
struct ServiceManagedTestCatalog {
    inner: Arc<dyn Catalog>,
    service_root: String,
    create_table_calls: AtomicUsize,
    drop_table_calls: AtomicUsize,
    injected: CommitInjection,
    stamped_operation_id: Mutex<Option<String>>,
}

impl ServiceManagedTestCatalog {
    fn new(inner: Arc<dyn Catalog>, service_root: String, injected: CommitInjection) -> Self {
        Self {
            inner,
            service_root,
            create_table_calls: AtomicUsize::new(0),
            drop_table_calls: AtomicUsize::new(0),
            injected,
            stamped_operation_id: Mutex::new(None),
        }
    }

    fn create_table_calls(&self) -> usize {
        self.create_table_calls.load(Ordering::SeqCst)
    }

    fn drop_table_calls(&self) -> usize {
        self.drop_table_calls.load(Ordering::SeqCst)
    }

    fn captured_operation_id(&self) -> String {
        self.stamped_operation_id
            .lock()
            .expect("capture lock")
            .clone()
            .expect("the commit must stamp an engine.operation-id")
    }
}

impl Catalog for ServiceManagedTestCatalog {
    fn list_namespaces<'life0, 'life1, 'async_trait>(
        &'life0 self,
        parent: Option<&'life1 NamespaceIdent>,
    ) -> BoxedCatalogFuture<'async_trait, Vec<NamespaceIdent>>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.list_namespaces(parent)
    }

    fn create_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        properties: HashMap<String, String>,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::Namespace>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.create_namespace(namespace, properties)
    }

    fn get_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::Namespace>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.get_namespace(namespace)
    }

    fn namespace_exists<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, bool>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.namespace_exists(namespace)
    }

    fn update_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        properties: HashMap<String, String>,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.update_namespace(namespace, properties)
    }

    fn drop_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.drop_namespace(namespace)
    }

    fn list_tables<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, Vec<TableIdent>>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.list_tables(namespace)
    }

    fn create_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        creation: TableCreation,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.create_table_calls.fetch_add(1, Ordering::SeqCst);
        if creation.location.is_some() {
            return Box::pin(async {
                Err(iceberg::Error::new(
                    iceberg::ErrorKind::DataInvalid,
                    "The location of the table is generated by s3tables catalog, can't \
                         be set by user.",
                ))
            });
        }
        let mut creation = creation;
        creation.location = Some(format!(
            "{}/{}/{}",
            self.service_root,
            namespace.to_url_string(),
            creation.name
        ));
        self.inner.create_table(namespace, creation)
    }

    fn load_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.load_table(table)
    }

    fn drop_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.drop_table_calls.fetch_add(1, Ordering::SeqCst);
        self.inner.drop_table(table)
    }

    fn table_exists<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, bool>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.table_exists(table)
    }

    fn rename_table<'life0, 'life1, 'life2, 'async_trait>(
        &'life0 self,
        src: &'life1 TableIdent,
        dest: &'life2 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        'life2: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.rename_table(src, dest)
    }

    fn register_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
        metadata_location: String,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.register_table(table, metadata_location)
    }

    fn update_table<'life0, 'async_trait>(
        &'life0 self,
        mut commit: iceberg::TableCommit,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        Box::pin(async move {
            if let CommitInjection::UpdateTable(kind) = self.injected {
                let stamped = commit
                    .take_updates()
                    .iter()
                    .find_map(|update| match update {
                        iceberg::TableUpdate::AddSnapshot { snapshot } => snapshot
                            .summary()
                            .additional_properties
                            .get(repark_iceberg::write::merge::OPERATION_ID_PROP)
                            .cloned(),
                        _ => None,
                    });
                *self.stamped_operation_id.lock().expect("capture lock") = stamped;
                return Err(iceberg::Error::new(
                    kind,
                    "injected commit failure on update_table (service-managed abort pin)",
                ));
            }
            self.inner.update_table(commit).await
        })
    }

    // The staged-publish seams have DEFAULT trait impls.
    fn publish_create_table<'life0, 'async_trait>(
        &'life0 self,
        table: iceberg::table::Table,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        Box::pin(async move {
            if let CommitInjection::PublishCreate(kind) = self.injected {
                return Err(iceberg::Error::new(
                    kind,
                    "injected commit failure on publish_create_table (staged abort pin)",
                ));
            }
            self.inner.publish_create_table(table).await
        })
    }

    fn publish_replace_table<'life0, 'async_trait>(
        &'life0 self,
        table: iceberg::table::Table,
        expected_base_metadata_location: Option<String>,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        self.inner
            .publish_replace_table(table, expected_base_metadata_location)
    }
}

/// A context + registry.
async fn setup_service_managed(
    wh: &TempDir,
    injected: CommitInjection,
) -> (
    SessionContext,
    CatalogRegistry,
    Arc<ServiceManagedTestCatalog>,
) {
    let (ctx, catalogs, svc) = setup_wrapped(
        wh,
        injected,
        "svc",
        LocationPolicy::ServiceManagedLocation,
        HashMap::new(),
    )
    .await;
    (ctx, catalogs, svc)
}

async fn setup_staged(
    wh: &TempDir,
    injected: CommitInjection,
) -> (
    SessionContext,
    CatalogRegistry,
    Arc<ServiceManagedTestCatalog>,
) {
    let warehouse = wh.path().to_str().unwrap().to_string();
    setup_wrapped(
        wh,
        injected,
        "glue_like",
        LocationPolicy::RequireExplicitLocation,
        HashMap::from([("location".to_string(), format!("{warehouse}/staged-sales"))]),
    )
    .await
}

async fn setup_wrapped(
    wh: &TempDir,
    injected: CommitInjection,
    catalog_name: &str,
    policy: LocationPolicy,
    namespace_properties: HashMap<String, String>,
) -> (
    SessionContext,
    CatalogRegistry,
    Arc<ServiceManagedTestCatalog>,
) {
    let warehouse = wh.path().to_str().unwrap().to_string();
    let inner: Arc<dyn Catalog> = Arc::new(
        MemoryCatalogBuilder::default()
            .with_storage_factory(Arc::new(LocalFsStorageFactory))
            .load(
                "memory",
                HashMap::from([(MEMORY_CATALOG_WAREHOUSE.to_string(), warehouse.clone())]),
            )
            .await
            .unwrap(),
    );
    inner
        .create_namespace(
            &NamespaceIdent::new("sales".to_string()),
            namespace_properties,
        )
        .await
        .unwrap();
    let svc = Arc::new(ServiceManagedTestCatalog::new(
        inner,
        format!("{warehouse}/svc-assigned"),
        injected,
    ));
    let handle: Arc<dyn Catalog> = svc.clone();

    let ctx = SessionContext::new();
    for rule in repark_functions::analyzer_rules() {
        ctx.add_analyzer_rule(rule);
    }
    repark_iceberg::catalog::register_iceberg_catalog(&ctx, catalog_name, handle.clone())
        .await
        .unwrap();
    register_source(&ctx, "src", &[(1, "a"), (2, "b"), (3, "c")]);

    let mut catalogs = CatalogRegistry::new();
    catalogs.insert(catalog_name.to_string(), handle, policy);
    (ctx, catalogs, svc)
}

fn sales_ident(table: &str) -> TableIdent {
    TableIdent::new(NamespaceIdent::new("sales".to_string()), table.to_string())
}

/// P1.
#[tokio::test]
async fn ctas_service_managed_creates_first_appends_and_reads_back() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.t USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect("service-managed CTAS must route create-first, not the staged location path");

    assert_eq!(svc.create_table_calls(), 1, "exactly one catalog create");
    assert_eq!(svc.drop_table_calls(), 0, "no abort on the happy path");
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.t").await,
        3,
        "all SELECT rows land in the created table"
    );
    let loaded = catalogs["svc"].load_table(&sales_ident("t")).await.unwrap();
    assert!(
        loaded
            .metadata()
            .location()
            .starts_with(&format!("{}/svc-assigned", wh.path().to_str().unwrap())),
        "table lives at the SERVICE-assigned location, not a namespace-derived one \
             (got `{}`)",
        loaded.metadata().location()
    );
    assert_eq!(
        loaded.metadata().snapshots().count(),
        1,
        "one fast-append commit = one snapshot"
    );
}

/// P2.
#[tokio::test]
async fn ctas_service_managed_partitioned_fans_out_and_reads_back() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.p USING iceberg PARTITIONED BY (name) AS \
             SELECT * FROM src",
    )
    .await
    .expect("partitioned service-managed CTAS");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.p").await,
        3,
        "partitioned fanout writes every row"
    );
    let loaded = catalogs["svc"].load_table(&sales_ident("p")).await.unwrap();
    assert!(
        !loaded
            .metadata()
            .default_partition_spec()
            .is_unpartitioned(),
        "the identity spec rode the creation"
    );
}

/// P3 — empty SELECT: the created empty table IS the result; NO snapshot is stamped.
#[tokio::test]
async fn ctas_service_managed_empty_select_creates_table_without_snapshot() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.e USING iceberg AS SELECT * FROM src WHERE id > 99",
    )
    .await
    .expect("empty service-managed CTAS still creates the table");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(rows(&ctx, &catalogs, "SELECT * FROM svc.sales.e").await, 0);
    let loaded = catalogs["svc"].load_table(&sales_ident("e")).await.unwrap();
    assert!(
        loaded.metadata().current_snapshot().is_none(),
        "empty CTAS commits NO snapshot"
    );
}

/// P4.
#[tokio::test]
async fn ctas_service_managed_commit_failure_drops_the_created_table() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(
        &wh,
        CommitInjection::UpdateTable(iceberg::ErrorKind::Unexpected),
    )
    .await;
    let err = execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.bad USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect_err("injected commit failure must surface");
    let msg = err.to_string();
    assert!(
        msg.contains("create-first abort") && msg.contains("injected commit failure"),
        "error names the abort AND the original failure: {msg}"
    );
    assert_eq!(svc.create_table_calls(), 1, "the create happened");
    assert_eq!(svc.drop_table_calls(), 1, "the abort dropped the table");
    assert!(
        !catalogs["svc"]
            .table_exists(&sales_ident("bad"))
            .await
            .unwrap(),
        "no half-created table survives the abort"
    );
}

#[tokio::test]
async fn ctas_service_managed_commit_state_unknown_keeps_table_and_surfaces_class() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(
        &wh,
        CommitInjection::UpdateTable(iceberg::ErrorKind::CommitStateUnknown),
    )
    .await;
    let error = execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.t USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect_err("the ambiguous commit outcome must surface");
    assert_eq!(svc.create_table_calls(), 1, "the create happened");
    assert_eq!(
        svc.drop_table_calls(),
        0,
        "an ambiguous commit is NOT abort-dropped — the create may have landed"
    );
    assert!(
        catalogs["svc"]
            .table_exists(&sales_ident("t"))
            .await
            .unwrap(),
        "the possibly-committed table stays for the operator (or an IF NOT EXISTS retry)"
    );
    match repark_core::engine_err(error) {
        repark_core::Error::CommitStateUnknown {
            operation_id,
            message,
        } => {
            assert!(
                message.contains("injected commit failure"),
                "the original commit error message survives: {message}"
            );
            assert_eq!(
                operation_id.as_deref(),
                Some(svc.captured_operation_id().as_str()),
                "the exception carries the operation id the commit attempted to stamp"
            );
        }
        other => panic!("expected Error::CommitStateUnknown, got {other:?}"),
    }
}

#[tokio::test]
async fn ctas_staged_commit_state_unknown_surfaces_class_without_operation_id() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_staged(
        &wh,
        CommitInjection::PublishCreate(iceberg::ErrorKind::CommitStateUnknown),
    )
    .await;
    let error = execute(
        &ctx,
        &catalogs,
        "CREATE TABLE glue_like.sales.t USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect_err("the ambiguous publish must surface");
    assert_eq!(
        svc.create_table_calls(),
        0,
        "the staged path publishes, it never create_table's"
    );
    assert_eq!(
        svc.drop_table_calls(),
        0,
        "the staged path never abort-drops"
    );
    match repark_core::engine_err(error) {
        repark_core::Error::CommitStateUnknown { operation_id, .. } => {
            assert_eq!(
                operation_id, None,
                "the staged publish path mints no engine.operation-id"
            );
        }
        other => panic!("expected Error::CommitStateUnknown, got {other:?}"),
    }
}

/// P5.
#[tokio::test]
async fn ctas_or_replace_on_service_managed_existing_table_stays_staged_replace() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.r USING iceberg AS SELECT * FROM src",
    )
    .await
    .unwrap();
    execute(
        &ctx,
        &catalogs,
        "CREATE OR REPLACE TABLE svc.sales.r USING iceberg AS \
             SELECT * FROM src WHERE id = 1",
    )
    .await
    .expect("OR REPLACE on an existing service-managed table uses the replace path");
    assert_eq!(
        svc.create_table_calls(),
        1,
        "replace must NOT call catalog create_table again"
    );
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.r").await,
        1,
        "the replacement definition's rows are served"
    );
}

#[tokio::test]
async fn ctas_service_managed_from_view_typed_batches_round_trips() {
    let warehouse = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&warehouse, CommitInjection::None).await;
    register_view_typed_source(&ctx, "viewsrc");
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.viewtyped USING iceberg AS SELECT * FROM viewsrc",
    )
    .await
    .expect("service-managed unpartitioned CTAS from Utf8View/BinaryView must commit");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(svc.drop_table_calls(), 0);
    let batches = execute(
        &ctx,
        &catalogs,
        "SELECT id, name FROM svc.sales.viewtyped ORDER BY id",
    )
    .await
    .unwrap()
    .collect()
    .await
    .unwrap();
    let mut names = Vec::new();
    for batch in &batches {
        let column = batch.column(1);
        let utf8 = datafusion::arrow::compute::cast(column, &DataType::Utf8).unwrap();
        let array = utf8.as_any().downcast_ref::<StringArray>().unwrap();
        for index in 0..batch.num_rows() {
            if array.is_null(index) {
                names.push(None);
            } else {
                names.push(Some(array.value(index).to_string()));
            }
        }
    }
    assert_eq!(
        names,
        vec![Some("a".to_string()), None, Some("c".to_string())]
    );
}

async fn service_managed_ops(catalogs: &CatalogRegistry, table: &str) -> Vec<String> {
    let loaded = catalogs["svc"]
        .load_table(&sales_ident(table))
        .await
        .unwrap();
    let mut snapshots: Vec<_> = loaded.metadata().snapshots().cloned().collect();
    snapshots.sort_by_key(|snapshot| snapshot.sequence_number());
    snapshots
        .iter()
        .map(|snapshot| snapshot.summary().operation.as_str().to_string())
        .collect()
}

#[tokio::test]
async fn ctas_service_managed_rtas_creating_the_table_records_overwrite() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE OR REPLACE TABLE svc.sales.rn USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect("service-managed new-table RTAS");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(service_managed_ops(&catalogs, "rn").await, ["overwrite"]);
    assert_eq!(rows(&ctx, &catalogs, "SELECT * FROM svc.sales.rn").await, 3);
}

#[tokio::test]
async fn ctas_service_managed_empty_rtas_records_delete_then_delete() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    let sql = "CREATE OR REPLACE TABLE svc.sales.re USING iceberg AS \
               SELECT * FROM src WHERE id > 99";
    execute(&ctx, &catalogs, sql)
        .await
        .expect("empty new-table RTAS");
    assert_eq!(service_managed_ops(&catalogs, "re").await, ["delete"]);
    execute(&ctx, &catalogs, sql)
        .await
        .expect("empty RTAS over the existing table");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(
        service_managed_ops(&catalogs, "re").await,
        ["delete", "delete"]
    );
    assert_eq!(rows(&ctx, &catalogs, "SELECT * FROM svc.sales.re").await, 0);
}

#[tokio::test]
async fn ctas_service_managed_plain_ctas_records_append() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, _svc) = setup_service_managed(&wh, CommitInjection::None).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.pa USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect("plain service-managed CTAS");
    assert_eq!(service_managed_ops(&catalogs, "pa").await, ["append"]);
}

#[tokio::test]
async fn ctas_custom_location_on_service_managed_catalog_refuses_loud() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    let refused = execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.custom LOCATION '/tmp/nope' AS SELECT * FROM src",
    )
    .await
    .expect_err("a custom LOCATION on a service-managed catalog must refuse");
    assert!(
        refused.to_string().contains("LOCATION") && refused.to_string().contains("service-managed"),
        "got: {refused}"
    );
    assert_eq!(
        svc.create_table_calls(),
        0,
        "the refusal precedes any catalog write"
    );
}

#[tokio::test]
async fn service_managed_create_and_ctas_stamp_the_session_owner() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, CommitInjection::None).await;
    let mut owner = repark_core::DescribeOwnerConfig::default();
    owner.owner = "svc_owner".to_string();
    ctx.state_ref()
        .write()
        .config_mut()
        .options_mut()
        .extensions
        .insert(owner);
    for sql in [
        "CREATE TABLE svc.sales.owned_ctas USING iceberg AS SELECT * FROM src",
        "CREATE TABLE svc.sales.owned_schema (id BIGINT) USING iceberg",
    ] {
        execute(&ctx, &catalogs, sql)
            .await
            .unwrap_or_else(|error| panic!("{sql} must plan: {error}"))
            .collect()
            .await
            .unwrap_or_else(|error| panic!("{sql} must execute: {error}"));
    }
    assert_eq!(
        svc.create_table_calls(),
        2,
        "both creates are service-managed"
    );
    for table in ["owned_ctas", "owned_schema"] {
        let loaded = catalogs["svc"]
            .load_table(&sales_ident(table))
            .await
            .unwrap();
        assert_eq!(
            loaded
                .metadata()
                .properties()
                .get("owner")
                .map(String::as_str),
            Some("svc_owner"),
            "{table} must store the session owner"
        );
    }
}
