/// =======================================================================================
/// Service-managed CTAS pins (S3 Tables create-first flow, `ServiceManagedLocation`).
/// The test catalog mirrors service-assigned locations and exposes a commit fault for the
/// drop-on-abort seam.
/// =======================================================================================
use super::super::*;
use super::common::*;
use std::future::Future;
use std::pin::Pin;
use std::sync::atomic::{AtomicUsize, Ordering};

type BoxedCatalogFuture<'a, T> = Pin<Box<dyn Future<Output = iceberg::Result<T>> + Send + 'a>>;

/// Mirrors the fork's service-assigned location contract and can fail at commit time.
#[derive(Debug)]
struct ServiceManagedTestCatalog {
    inner: Arc<dyn Catalog>,
    service_root: String,
    create_table_calls: AtomicUsize,
    drop_table_calls: AtomicUsize,
    fail_update_table: bool,
}

impl ServiceManagedTestCatalog {
    fn new(inner: Arc<dyn Catalog>, service_root: String, fail_update_table: bool) -> Self {
        Self {
            inner,
            service_root,
            create_table_calls: AtomicUsize::new(0),
            drop_table_calls: AtomicUsize::new(0),
            fail_update_table,
        }
    }

    fn create_table_calls(&self) -> usize {
        self.create_table_calls.load(Ordering::SeqCst)
    }

    fn drop_table_calls(&self) -> usize {
        self.drop_table_calls.load(Ordering::SeqCst)
    }
}

impl Catalog for ServiceManagedTestCatalog {
    fn list_namespaces<'life0, 'life1, 'async_trait>(
        &'life0 self,
        parent: Option<&'life1 NamespaceIdent>,
    ) -> BoxedCatalogFuture<'async_trait, Vec<NamespaceIdent>>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.list_namespaces(parent)
    }

    fn create_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        properties: HashMap<String, String>,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::Namespace>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.create_namespace(namespace, properties)
    }

    fn get_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::Namespace>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.get_namespace(namespace)
    }

    fn namespace_exists<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, bool>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.namespace_exists(namespace)
    }

    fn update_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        properties: HashMap<String, String>,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.update_namespace(namespace, properties)
    }

    fn drop_namespace<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.drop_namespace(namespace)
    }

    fn list_tables<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
    ) -> BoxedCatalogFuture<'async_trait, Vec<TableIdent>>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.list_tables(namespace)
    }

    fn create_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        namespace: &'life1 NamespaceIdent,
        creation: TableCreation,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.create_table_calls.fetch_add(1, Ordering::SeqCst);
        if creation.location.is_some() {
            return Box::pin(async {
                Err(iceberg::Error::new(
                    iceberg::ErrorKind::DataInvalid,
                    "The location of the table is generated by s3tables catalog, can't \
                         be set by user.",
                ))
            });
        }
        let mut creation = creation;
        creation.location = Some(format!(
            "{}/{}/{}",
            self.service_root,
            namespace.to_url_string(),
            creation.name
        ));
        self.inner.create_table(namespace, creation)
    }

    fn load_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.load_table(table)
    }

    fn drop_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.drop_table_calls.fetch_add(1, Ordering::SeqCst);
        self.inner.drop_table(table)
    }

    fn table_exists<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, bool>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.table_exists(table)
    }

    fn rename_table<'life0, 'life1, 'life2, 'async_trait>(
        &'life0 self,
        src: &'life1 TableIdent,
        dest: &'life2 TableIdent,
    ) -> BoxedCatalogFuture<'async_trait, ()>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        'life2: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.rename_table(src, dest)
    }

    fn register_table<'life0, 'life1, 'async_trait>(
        &'life0 self,
        table: &'life1 TableIdent,
        metadata_location: String,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        'life1: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.register_table(table, metadata_location)
    }

    fn update_table<'life0, 'async_trait>(
        &'life0 self,
        commit: iceberg::TableCommit,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        Box::pin(async move {
            if self.fail_update_table {
                return Err(iceberg::Error::new(
                    iceberg::ErrorKind::Unexpected,
                    "injected commit failure on update_table (service-managed abort pin)",
                ));
            }
            self.inner.update_table(commit).await
        })
    }

    // The staged-publish seams have DEFAULT trait impls (`publish_replace_table` errors
    // `FeatureUnsupported`); delegate so the inner memory catalog's overrides stay
    // reachable through the wrapper. NOTE the real fork `S3TablesCatalog` does NOT
    // override `publish_replace_table` at pin `14921e78` — CTAS OR REPLACE on real
    // S3 Tables fails loudly at publish.
    fn publish_create_table<'life0, 'async_trait>(
        &'life0 self,
        table: iceberg::table::Table,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        self.inner.publish_create_table(table)
    }

    fn publish_replace_table<'life0, 'async_trait>(
        &'life0 self,
        table: iceberg::table::Table,
        expected_base_metadata_location: Option<String>,
    ) -> BoxedCatalogFuture<'async_trait, iceberg::table::Table>
    where
        'life0: 'async_trait,
        Self: 'async_trait,
    {
        self.inner
            .publish_replace_table(table, expected_base_metadata_location)
    }
}

/// A context + registry with the service-managed catalog `svc` whose `sales` namespace
/// deliberately carries NO `location` property (the S3 Tables shape that fails the staged
/// path), plus the standard 3-row `src` source.
async fn setup_service_managed(
    wh: &TempDir,
    fail_update_table: bool,
) -> (
    SessionContext,
    CatalogRegistry,
    Arc<ServiceManagedTestCatalog>,
) {
    let warehouse = wh.path().to_str().unwrap().to_string();
    let inner: Arc<dyn Catalog> = Arc::new(
        MemoryCatalogBuilder::default()
            .with_storage_factory(Arc::new(LocalFsStorageFactory))
            .load(
                "memory",
                HashMap::from([(MEMORY_CATALOG_WAREHOUSE.to_string(), warehouse.clone())]),
            )
            .await
            .unwrap(),
    );
    inner
        .create_namespace(&NamespaceIdent::new("sales".to_string()), HashMap::new())
        .await
        .unwrap();
    let svc = Arc::new(ServiceManagedTestCatalog::new(
        inner,
        format!("{warehouse}/svc-assigned"),
        fail_update_table,
    ));
    let handle: Arc<dyn Catalog> = svc.clone();

    let ctx = SessionContext::new();
    for rule in repark_functions::analyzer_rules() {
        ctx.add_analyzer_rule(rule);
    }
    repark_iceberg::catalog::register_iceberg_catalog(&ctx, "svc", handle.clone())
        .await
        .unwrap();
    register_source(&ctx, "src", &[(1, "a"), (2, "b"), (3, "c")]);

    let mut catalogs = CatalogRegistry::new();
    catalogs.insert(
        "svc".to_string(),
        handle,
        LocationPolicy::ServiceManagedLocation,
    );
    (ctx, catalogs, svc)
}

fn sales_ident(table: &str) -> TableIdent {
    TableIdent::new(NamespaceIdent::new("sales".to_string()), table.to_string())
}

/// P1 — the create-first happy path: a location-less namespace on a service-managed
/// catalog CTASes successfully (the staged path errors on exactly this shape — the A2
/// S3 Tables acceptance failure), the location is the SERVICE-assigned one, exactly one
/// `create_table` call carries NO caller location (the wrapper rejects one outright, so
/// success is itself the proof), and the data commits as ONE snapshot.
#[tokio::test]
async fn ctas_service_managed_creates_first_appends_and_reads_back() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, false).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.t USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect("service-managed CTAS must route create-first, not the staged location path");

    assert_eq!(svc.create_table_calls(), 1, "exactly one catalog create");
    assert_eq!(svc.drop_table_calls(), 0, "no abort on the happy path");
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.t").await,
        3,
        "all SELECT rows land in the created table"
    );
    let loaded = catalogs["svc"].load_table(&sales_ident("t")).await.unwrap();
    assert!(
        loaded
            .metadata()
            .location()
            .starts_with(&format!("{}/svc-assigned", wh.path().to_str().unwrap())),
        "table lives at the SERVICE-assigned location, not a namespace-derived one \
             (got `{}`)",
        loaded.metadata().location()
    );
    assert_eq!(
        loaded.metadata().snapshots().count(),
        1,
        "one fast-append commit = one snapshot"
    );
}

/// P2 — partitioned create-first: the `PARTITIONED BY` spec rides the location-less
/// `TableCreation` and the data routes through the partitioned fanout arm.
#[tokio::test]
async fn ctas_service_managed_partitioned_fans_out_and_reads_back() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, false).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.p USING iceberg PARTITIONED BY (name) AS \
             SELECT * FROM src",
    )
    .await
    .expect("partitioned service-managed CTAS");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.p").await,
        3,
        "partitioned fanout writes every row"
    );
    let loaded = catalogs["svc"].load_table(&sales_ident("p")).await.unwrap();
    assert!(
        !loaded
            .metadata()
            .default_partition_spec()
            .is_unpartitioned(),
        "the identity spec rode the creation"
    );
}

/// P3 — empty SELECT: the created empty table IS the result; NO snapshot is stamped
/// (a zero-file fast-append would stamp a pointless empty snapshot).
#[tokio::test]
async fn ctas_service_managed_empty_select_creates_table_without_snapshot() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, false).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.e USING iceberg AS SELECT * FROM src WHERE id > 99",
    )
    .await
    .expect("empty service-managed CTAS still creates the table");
    assert_eq!(svc.create_table_calls(), 1);
    assert_eq!(rows(&ctx, &catalogs, "SELECT * FROM svc.sales.e").await, 0);
    let loaded = catalogs["svc"].load_table(&sales_ident("e")).await.unwrap();
    assert!(
        loaded.metadata().current_snapshot().is_none(),
        "empty CTAS commits NO snapshot"
    );
}

/// P4 — drop-on-abort: create succeeds, the append COMMIT fails (injected), and the
/// just-created table is dropped — no half-created table survives, and the error names
/// both the failure and the abort. Mutation direction: disable the abort `drop_table`
/// call in `execute_ctas_service_managed` → the `table_exists` assert goes RED.
#[tokio::test]
async fn ctas_service_managed_commit_failure_drops_the_created_table() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, true).await;
    let err = execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.bad USING iceberg AS SELECT * FROM src",
    )
    .await
    .expect_err("injected commit failure must surface");
    let msg = err.to_string();
    assert!(
        msg.contains("create-first abort") && msg.contains("injected commit failure"),
        "error names the abort AND the original failure: {msg}"
    );
    assert_eq!(svc.create_table_calls(), 1, "the create happened");
    assert_eq!(svc.drop_table_calls(), 1, "the abort dropped the table");
    assert!(
        !catalogs["svc"]
            .table_exists(&sales_ident("bad"))
            .await
            .unwrap(),
        "no half-created table survives the abort"
    );
}

/// P5 — OR REPLACE of an EXISTING service-managed table stays on the staged-replace path
/// (the existing table's own service location is reused; `create_table` is NOT called
/// again — the service would reject it) and the new definition's rows win.
#[tokio::test]
async fn ctas_or_replace_on_service_managed_existing_table_stays_staged_replace() {
    let wh = TempDir::new().unwrap();
    let (ctx, catalogs, svc) = setup_service_managed(&wh, false).await;
    execute(
        &ctx,
        &catalogs,
        "CREATE TABLE svc.sales.r USING iceberg AS SELECT * FROM src",
    )
    .await
    .unwrap();
    execute(
        &ctx,
        &catalogs,
        "CREATE OR REPLACE TABLE svc.sales.r USING iceberg AS \
             SELECT * FROM src WHERE id = 1",
    )
    .await
    .expect("OR REPLACE on an existing service-managed table uses the replace path");
    assert_eq!(
        svc.create_table_calls(),
        1,
        "replace must NOT call catalog create_table again"
    );
    assert_eq!(
        rows(&ctx, &catalogs, "SELECT * FROM svc.sales.r").await,
        1,
        "the replacement definition's rows are served"
    );
}
