"""Hyperparameter tuning — ``ParamGridBuilder`` + ``CrossValidator`` (M4 / M6).

Pure Python orchestration over estimators (native LR or ext boosters). No new Rust
deps. Fold assignment is deterministic via SQL ``ROW_NUMBER`` + optional seed hash.
``parallelism > 1`` thread-pools independent (fold, paramMap) fits (M6); metrics are
order-independent sums so results match any parallelism.
"""

from __future__ import annotations

import contextlib
import itertools
import math
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

# === r23 QI1: idents ===
from repark._idents import quote_ident as _quote_ident
from repark.errors import IllegalArgumentException, PySparkTypeError
from repark.ml.base import Estimator, Model, _require_repark_dataframe
from repark.ml.evaluation import Evaluator
from repark.ml.param import Param, TypeConverters


class ParamGridBuilder:
    """Build a cartesian product of ``Param`` maps (Spark ``ParamGridBuilder``)."""

    def __init__(self) -> None:
        """Empty grid; call :meth:`addGrid` / :meth:`baseOn` then :meth:`build`."""
        self._grids: list[tuple[Param[Any], list[Any]]] = []
        self._base: dict[Param[Any], Any] = {}

    def baseOn(self, *args: Any) -> ParamGridBuilder:
        """Fix base params. Accepts a dict or alternating Param/value pairs."""
        if len(args) == 1 and isinstance(args[0], dict):
            for param, value in args[0].items():
                if not isinstance(param, Param):
                    raise PySparkTypeError(
                        f"ParamGridBuilder.baseOn keys must be Param, got {type(param).__name__}"
                    )
                self._base[param] = value
            return self
        if len(args) % 2 != 0:
            raise IllegalArgumentException(
                "ParamGridBuilder.baseOn expects a dict or even-length Param/value pairs"
            )
        for index in range(0, len(args), 2):
            param = args[index]
            value = args[index + 1]
            if not isinstance(param, Param):
                raise PySparkTypeError(
                    "ParamGridBuilder.baseOn expects Param at even index, "
                    f"got {type(param).__name__}"
                )
            self._base[param] = value
        return self

    def addGrid(self, param: Param[Any], values: list[Any] | tuple[Any, ...]) -> ParamGridBuilder:
        """Add a param axis (list of candidate values)."""
        if not isinstance(param, Param):
            raise PySparkTypeError(
                f"ParamGridBuilder.addGrid param must be Param, got {type(param).__name__}"
            )
        if not isinstance(values, (list, tuple)):
            raise PySparkTypeError(
                f"ParamGridBuilder.addGrid values must be list/tuple, got {type(values).__name__}"
            )
        if len(values) == 0:
            raise IllegalArgumentException("ParamGridBuilder.addGrid values must be non-empty")
        self._grids.append((param, list(values)))
        return self

    def build(self) -> list[dict[Param[Any], Any]]:
        """Cartesian product of grids over the base map (Spark ``build``)."""
        if not self._grids:
            return [dict(self._base)]
        axes = [grid[1] for grid in self._grids]
        params = [grid[0] for grid in self._grids]
        maps: list[dict[Param[Any], Any]] = []
        for combo in itertools.product(*axes):
            param_map = dict(self._base)
            for param, value in zip(params, combo, strict=True):
                param_map[param] = value
            maps.append(param_map)
        return maps


class CrossValidator(Estimator["CrossValidatorModel"]):
    """K-fold cross-validation over an estimator + param grid (Spark ``CrossValidator``).

    Works with native estimators (e.g. ``LinearRegression``) and ext estimators.
    """

    def __init__(
        self,
        *,
        estimator: Estimator[Any] | None = None,
        estimatorParamMaps: list[dict[Param[Any], Any]] | None = None,  # noqa: N803
        evaluator: Evaluator | None = None,
        numFolds: int | None = None,  # noqa: N803
        seed: int | None = None,
        parallelism: int | None = None,
        collectSubModels: bool | None = None,  # noqa: N803
    ) -> None:
        """Optional kwargs mirror Spark constructor names."""
        super().__init__()
        self.estimator: Param[Any] = Param(
            self, "estimator", "estimator to be cross-validated", TypeConverters.identity
        )
        self.estimatorParamMaps: Param[list[Any]] = Param(
            self,
            "estimatorParamMaps",
            "param maps generated by ParamGridBuilder",
            TypeConverters.identity,
        )
        self.evaluator: Param[Any] = Param(
            self, "evaluator", "evaluator used to select best model", TypeConverters.identity
        )
        self.numFolds: Param[int] = Param(
            self, "numFolds", "number of folds for cross validation", TypeConverters.toInt
        )
        self.seed: Param[int] = Param(self, "seed", "random seed", TypeConverters.toInt)
        self.parallelism: Param[int] = Param(
            self,
            "parallelism",
            "max worker threads for independent fold x paramMap fits (M6; 1 = sequential)",
            TypeConverters.toInt,
        )
        self.collectSubModels: Param[bool] = Param(
            self,
            "collectSubModels",
            "whether to collect submodels (accepted; not retained in v1)",
            TypeConverters.toBoolean,
        )
        self._setDefault(
            estimator=None,
            estimatorParamMaps=[],
            evaluator=None,
            numFolds=3,
            seed=0,
            parallelism=1,
            collectSubModels=False,
        )
        if estimator is not None:
            self.setEstimator(estimator)
        if estimatorParamMaps is not None:
            self.setEstimatorParamMaps(estimatorParamMaps)
        if evaluator is not None:
            self.setEvaluator(evaluator)
        if numFolds is not None:
            self.setNumFolds(numFolds)
        if seed is not None:
            self._set(seed=seed)
        if parallelism is not None:
            # Route through setter so ctor rejects < 1 (getParallelism's max(1, …) must not
            # silently clamp a hostile constructor value — octo M6 C1).
            self.setParallelism(int(parallelism))
        if collectSubModels is not None:
            self._set(collectSubModels=collectSubModels)

    def setEstimator(self, value: Estimator[Any]) -> CrossValidator:
        """Set estimator."""
        if not isinstance(value, Estimator):
            raise PySparkTypeError(f"estimator must be Estimator, got {type(value).__name__}")
        return self._set(estimator=value)

    def getEstimator(self) -> Estimator[Any]:
        """Get estimator."""
        value = self.getOrDefault(self.estimator)
        if value is None:
            raise IllegalArgumentException("CrossValidator.estimator is not set")
        return value  # type: ignore[no-any-return]

    def setEstimatorParamMaps(self, value: list[dict[Param[Any], Any]]) -> CrossValidator:
        """Set param maps."""
        if not isinstance(value, list):
            raise PySparkTypeError(f"estimatorParamMaps must be list, got {type(value).__name__}")
        return self._set(estimatorParamMaps=list(value))

    def getEstimatorParamMaps(self) -> list[dict[Param[Any], Any]]:
        """Get param maps."""
        return list(self.getOrDefault(self.estimatorParamMaps))  # type: ignore[no-any-return]

    def setEvaluator(self, value: Evaluator) -> CrossValidator:
        """Set evaluator."""
        if not isinstance(value, Evaluator):
            raise PySparkTypeError(f"evaluator must be Evaluator, got {type(value).__name__}")
        return self._set(evaluator=value)

    def getEvaluator(self) -> Evaluator:
        """Get evaluator."""
        value = self.getOrDefault(self.evaluator)
        if value is None:
            raise IllegalArgumentException("CrossValidator.evaluator is not set")
        return value  # type: ignore[no-any-return]

    def setNumFolds(self, value: int) -> CrossValidator:
        """Set number of folds (>= 2)."""
        if int(value) < 2:
            raise IllegalArgumentException(f"numFolds must be >= 2, got {value}")
        return self._set(numFolds=int(value))

    def getNumFolds(self) -> int:
        """Get number of folds."""
        return int(self.getOrDefault(self.numFolds))

    def setSeed(self, value: int) -> CrossValidator:
        """Set seed."""
        return self._set(seed=int(value))

    def getSeed(self) -> int:
        """Get seed."""
        return int(self.getOrDefault(self.seed))

    def _with_fold_column(self, frame: Any, num_folds: int, seed: int) -> tuple[Any, str, str]:
        """Attach a deterministic ``__cv_fold`` column and **materialize** fold labels once.

        Fold assignment uses ``ROW_NUMBER`` + hash. Without materialization, each later
        ``fit``/``transform``/``to_arrow`` re-executes the window over a lazy plan and can
        reassign folds (same bug class as F-Q1-009 / ``_materialize_rid_view``) — poisoning
        ``bestModel`` selection (octo C1-L-001).
        """
        fold_col = f"__cv_fold_{uuid.uuid4().hex[:8]}"
        view = f"__repark_cv_src_{uuid.uuid4().hex[:12]}"
        mat_view = f"__repark_cv_mat_{uuid.uuid4().hex[:12]}"
        frame.createOrReplaceTempView(view)
        # Deterministic fold: hash(row_number || seed) % num_folds — stable on row order.
        sql = (
            f"SELECT {view}.*, "
            f"MOD(abs(hash(concat(CAST(ROW_NUMBER() OVER (ORDER BY 1) AS VARCHAR), "
            f"'_', CAST({int(seed)} AS VARCHAR)))), {int(num_folds)}) AS \"{fold_col}\" "
            f"FROM {view}"
        )
        try:
            try:
                folded_lazy = frame._spawn(frame._session.sql(sql))
            except Exception:
                # Fallback when hash/concat unavailable: sequential modulo.
                sql = (
                    f"SELECT {view}.*, "
                    f'MOD(ROW_NUMBER() OVER (ORDER BY 1) - 1, {int(num_folds)}) AS "{fold_col}" '
                    f"FROM {view}"
                )
                folded_lazy = frame._spawn(frame._session.sql(sql))
            # Collect once into a MemTable so fold labels are scan-stable.
            frame._session.materialize_as_temp_view(mat_view, folded_lazy._inner)
            folded = frame._spawn(frame._session.sql(f"SELECT * FROM {mat_view}"))
        except Exception:
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(mat_view)
            raise
        finally:
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(view)
        return folded, fold_col, mat_view

    def getParallelism(self) -> int:
        """Get max worker threads for independent fold x paramMap fits."""
        return max(1, int(self.getOrDefault(self.parallelism)))

    def setParallelism(self, value: int) -> CrossValidator:
        """Set max worker threads (>= 1)."""
        if int(value) < 1:
            raise IllegalArgumentException(f"parallelism must be >= 1, got {value}")
        return self._set(parallelism=int(value))

    def _split_fold(
        self, frame: Any, folded: Any, fold_col: str, fold_index: int
    ) -> tuple[Any, Any, str]:
        """Build train/test frames for one fold; return ``(train, test, train_view)``."""
        quoted_fold = _quote_ident(fold_col)
        train_view = f"__repark_cv_tr_{uuid.uuid4().hex[:12]}"
        folded.createOrReplaceTempView(train_view)
        try:
            train = frame._spawn(
                frame._session.sql(
                    f"SELECT * EXCLUDE ({quoted_fold}) FROM {train_view} "
                    f"WHERE {quoted_fold} <> {fold_index}"
                )
            )
        except Exception:
            cols = [name for name in folded.columns if name != fold_col]
            col_sql = ", ".join(_quote_ident(name) for name in cols)
            train = frame._spawn(
                frame._session.sql(
                    f"SELECT {col_sql} FROM {train_view} WHERE {quoted_fold} <> {fold_index}"
                )
            )
        try:
            test = frame._spawn(
                frame._session.sql(
                    f"SELECT * EXCLUDE ({quoted_fold}) FROM {train_view} "
                    f"WHERE {quoted_fold} = {fold_index}"
                )
            )
        except Exception:
            cols = [name for name in folded.columns if name != fold_col]
            col_sql = ", ".join(_quote_ident(name) for name in cols)
            test = frame._spawn(
                frame._session.sql(
                    f"SELECT {col_sql} FROM {train_view} WHERE {quoted_fold} = {fold_index}"
                )
            )
        return train, test, train_view

    @staticmethod
    def _eval_fold_param(
        estimator: Estimator[Any],
        evaluator: Evaluator,
        train: Any,
        test: Any,
        param_map: dict[Param[Any], Any],
        map_index: int,
        fold_index: int,
    ) -> tuple[int, int, float]:
        """Fit one param map on train, score on test. Returns ``(map_index, fold_index, score)``."""
        model = estimator.fit(train, params=param_map if param_map else None)
        predictions = model.transform(test)
        score = float(evaluator.evaluate(predictions))
        if math.isnan(score):
            raise IllegalArgumentException(
                "CrossValidator.fit: fold evaluation returned NaN "
                f"(map_index={map_index}, fold_index={fold_index}); "
                "refuse silent bestModel selection (e.g. R2 on a "
                "zero-variance label fold)"
            )
        return map_index, fold_index, score

    def _fit(self, dataset: Any) -> CrossValidatorModel:
        """K-fold grid search; refit best param map on full data.

        When ``parallelism > 1``, independent (fold, paramMap) fits run on a thread pool
        (M6). Fold labels are still materialized once; train/test frames are built
        sequentially per fold before the parallel fan-out so view registration stays
        single-threaded. Metric accumulation is a pure sum → determinism across
        parallelism levels.
        """
        frame = _require_repark_dataframe(dataset, verb="CrossValidator.fit")
        estimator = self.getEstimator()
        evaluator = self.getEvaluator()
        param_maps = self.getEstimatorParamMaps()
        if not param_maps:
            param_maps = [{}]
        num_folds = self.getNumFolds()
        seed = self.getSeed()
        parallelism = self.getParallelism()

        folded, fold_col, mat_view = self._with_fold_column(frame, num_folds, seed)

        metrics: list[float] = [0.0] * len(param_maps)
        train_views: list[str] = []
        try:
            # Build all fold splits first (view registration is sequential).
            fold_splits: list[tuple[int, Any, Any]] = []
            for fold_index in range(num_folds):
                train, test, train_view = self._split_fold(frame, folded, fold_col, fold_index)
                train_views.append(train_view)
                fold_splits.append((fold_index, train, test))

            jobs: list[tuple[int, int, Any, Any, dict[Param[Any], Any]]] = []
            for fold_index, train, test in fold_splits:
                for map_index, param_map in enumerate(param_maps):
                    jobs.append((map_index, fold_index, train, test, param_map))

            if parallelism <= 1 or len(jobs) <= 1:
                for map_index, fold_index, train, test, param_map in jobs:
                    _, _, score = self._eval_fold_param(
                        estimator, evaluator, train, test, param_map, map_index, fold_index
                    )
                    metrics[map_index] += score
            else:
                workers = min(parallelism, len(jobs))
                with ThreadPoolExecutor(max_workers=workers) as pool:
                    futures = [
                        pool.submit(
                            self._eval_fold_param,
                            estimator,
                            evaluator,
                            train,
                            test,
                            param_map,
                            map_index,
                            fold_index,
                        )
                        for map_index, fold_index, train, test, param_map in jobs
                    ]
                    # Collect then sum on the main thread — float += is not atomic across
                    # threads (lost updates would break parallelism determinism).
                    fold_scores = [future.result() for future in as_completed(futures)]
                for map_index, _fold_index, score in fold_scores:
                    metrics[map_index] += score
        finally:
            for train_view in train_views:
                with contextlib.suppress(Exception):
                    frame._session.drop_temp_view(train_view)
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(mat_view)

        avg_metrics = [value / float(num_folds) for value in metrics]
        if any(math.isnan(value) for value in avg_metrics):
            raise IllegalArgumentException(
                "CrossValidator.fit: avgMetrics contains NaN; cannot select bestModel"
            )
        larger_better = bool(evaluator.isLargerBetter())
        if larger_better:
            best_index = max(range(len(avg_metrics)), key=lambda index: avg_metrics[index])
        else:
            best_index = min(range(len(avg_metrics)), key=lambda index: avg_metrics[index])
        best_map = param_maps[best_index]
        best_model = estimator.fit(frame, params=best_map if best_map else None)
        result = CrossValidatorModel(
            bestModel=best_model,
            avgMetrics=avg_metrics,
            estimator=estimator,
            evaluator=evaluator,
            estimatorParamMaps=param_maps,
            numFolds=num_folds,
        )
        result.uid = self.uid
        return result


class CrossValidatorModel(Model):
    """Fitted ``CrossValidator`` — exposes ``bestModel`` + ``avgMetrics``."""

    def __init__(
        self,
        *,
        bestModel: Model | None = None,  # noqa: N803
        avgMetrics: list[float] | None = None,  # noqa: N803
        estimator: Estimator[Any] | None = None,
        evaluator: Evaluator | None = None,
        estimatorParamMaps: list[dict[Param[Any], Any]] | None = None,  # noqa: N803
        numFolds: int = 3,  # noqa: N803
    ) -> None:
        """Store best model and fold-averaged metrics (no training rows)."""
        super().__init__()
        self.bestModel = bestModel
        self.avgMetrics = list(avgMetrics or [])
        self.estimator = estimator
        self.evaluator = evaluator
        self.estimatorParamMaps = list(estimatorParamMaps or [])
        self.numFolds = int(numFolds)

    def _transform(self, dataset: Any) -> Any:
        """Delegate transform to ``bestModel``."""
        if self.bestModel is None:
            raise IllegalArgumentException("CrossValidatorModel has no bestModel")
        return self.bestModel.transform(dataset)

    def copy(self, extra: dict[Any, Any] | None = None) -> CrossValidatorModel:
        """Copy shell; forward ``extra`` onto bestModel so transform overrides apply (C4-L-002)."""
        # CrossValidatorModel has no predictionCol of its own — Param overrides for
        # transform(df, params) must land on bestModel (Spark delegates transform there).
        best = self.bestModel.copy(extra=extra) if self.bestModel is not None else None
        that = CrossValidatorModel(
            bestModel=best,
            avgMetrics=list(self.avgMetrics),
            estimator=self.estimator,
            evaluator=self.evaluator,
            estimatorParamMaps=list(self.estimatorParamMaps),
            numFolds=self.numFolds,
        )
        that.uid = self.uid
        return that


__all__ = [
    "CrossValidator",
    "CrossValidatorModel",
    "ParamGridBuilder",
]
