use std::sync::Arc;

use arrow::array::{Int32Array, RecordBatch, StringArray};
use repark_connect::{
    ConnectError, PgIdent, Privilege, QualifiedRelation, RowFallback, ScanSource, WritePath,
    WriteRefusal, WriteReport, WriteRequest,
};

use crate::live_pg::{Cell, LIVE, tag, url};
use crate::live_write::{Store, ids, no_backend_remains};
use crate::write::batch_of;

#[derive(Clone, Copy)]
enum Outcome {
    Rows(u64),
    Sqlstate(&'static str),
    Identity(&'static str),
    Generated(&'static str),
    Denied,
}

#[derive(Clone, Copy)]
struct Property {
    name: &'static str,
    ddl: &'static str,
    target: &'static str,
    columns: &'static [&'static str],
    batch: fn() -> RecordBatch,
    fallback: Option<RowFallback>,
    outcome: Outcome,
    signature: &'static str,
    expect: &'static str,
}

const TABLE: &str = "CREATE TABLE {s}.{t} (id int4, v text)";
const ROWS: &str =
    "SELECT COALESCE(pg_catalog.string_agg(id || ':' || v, ',' ORDER BY id), '') FROM {s}.{t}";
const FOUR: &str = "1:a,2:b,3:c,4:d";
const PAIR: &[&str] = &["id", "v"];

const PLAIN: Property = Property {
    name: "plain",
    ddl: TABLE,
    target: "{t}",
    columns: PAIR,
    batch: four,
    fallback: None,
    outcome: Outcome::Rows(4),
    signature: ROWS,
    expect: FOUR,
};

fn four() -> RecordBatch {
    batch_of(&[
        ("id", ids(1..5)),
        ("v", Arc::new(StringArray::from(vec!["a", "b", "c", "d"]))),
    ])
}

fn three() -> RecordBatch {
    four().slice(0, 3)
}

fn only_ids() -> RecordBatch {
    batch_of(&[("id", ids(1..5))])
}

fn id_and_tenfold() -> RecordBatch {
    batch_of(&[
        ("id", ids(1..5)),
        ("n", Arc::new(Int32Array::from(vec![10, 20, 30, 40]))),
    ])
}

fn v_then_id() -> RecordBatch {
    batch_of(&[
        ("v", Arc::new(StringArray::from(vec!["a", "b", "c", "d"]))),
        ("id", ids(1..5)),
    ])
}

fn twin_v() -> RecordBatch {
    batch_of(&[
        ("id", ids(1..5)),
        ("v", Arc::new(StringArray::from(vec!["a", "b", "a", "d"]))),
    ])
}

const COLUMNS: [Property; 7] = [
    Property {
        name: "identity_always_named",
        ddl: "CREATE TABLE {s}.{t} (id int4, n int4 GENERATED ALWAYS AS IDENTITY)",
        columns: &["id", "n"],
        batch: id_and_tenfold,
        outcome: Outcome::Identity("n"),
        signature: "SELECT pg_catalog.count(*)::text FROM {s}.{t}",
        expect: "0",
        ..PLAIN
    },
    Property {
        name: "identity_always_unnamed",
        ddl: "CREATE TABLE {s}.{t} (id int4, n int4 GENERATED ALWAYS AS IDENTITY)",
        columns: &["id"],
        batch: only_ids,
        signature: "SELECT pg_catalog.string_agg(id || ':' || n, ',' ORDER BY id) FROM {s}.{t}",
        expect: "1:1,2:2,3:3,4:4",
        ..PLAIN
    },
    Property {
        name: "identity_by_default_named",
        ddl: "CREATE TABLE {s}.{t} (id int4, n int4 GENERATED BY DEFAULT AS IDENTITY)",
        columns: &["id", "n"],
        batch: id_and_tenfold,
        signature: "SELECT pg_catalog.string_agg(id || ':' || n, ',' ORDER BY id) FROM {s}.{t}",
        expect: "1:10,2:20,3:30,4:40",
        ..PLAIN
    },
    Property {
        name: "generated_named",
        ddl: "CREATE TABLE {s}.{t} (id int4, n int4 GENERATED ALWAYS AS (id * 2) STORED)",
        columns: &["id", "n"],
        batch: id_and_tenfold,
        outcome: Outcome::Generated("n"),
        signature: "SELECT pg_catalog.count(*)::text FROM {s}.{t}",
        expect: "0",
        ..PLAIN
    },
    Property {
        name: "generated_unnamed",
        ddl: "CREATE TABLE {s}.{t} (id int4, n int4 GENERATED ALWAYS AS (id * 2) STORED)",
        columns: &["id"],
        batch: only_ids,
        signature: "SELECT pg_catalog.string_agg(id || ':' || n, ',' ORDER BY id) FROM {s}.{t}",
        expect: "1:2,2:4,3:6,4:8",
        ..PLAIN
    },
    Property {
        name: "defaults_for_the_unnamed",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text DEFAULT 'dflt', n int4 DEFAULT 5)",
        columns: &["id"],
        batch: only_ids,
        signature: "SELECT pg_catalog.string_agg(id || v || n, ',' ORDER BY id) FROM {s}.{t}",
        expect: "1dflt5,2dflt5,3dflt5,4dflt5",
        ..PLAIN
    },
    Property {
        name: "columns_in_the_write_order",
        columns: &["v", "id"],
        batch: v_then_id,
        ..PLAIN
    },
];

const RULES_AND_VIEWS: [Property; 8] = [
    Property {
        name: "rule_instead_nothing",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE RULE skip AS ON INSERT TO {s}.{t} DO INSTEAD NOTHING",
        fallback: Some(RowFallback::InsertRule),
        outcome: Outcome::Rows(0),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "rule_do_also",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text); CREATE TABLE {s}.{t}_audit (id int4);
              CREATE RULE also AS ON INSERT TO {s}.{t}
              DO ALSO INSERT INTO {s}.{t}_audit VALUES (NEW.id)",
        fallback: Some(RowFallback::InsertRule),
        signature: "SELECT (SELECT pg_catalog.count(*) FROM {s}.{t}) || '/' ||
                    (SELECT pg_catalog.string_agg(id::text, ',' ORDER BY id) FROM {s}.{t}_audit)",
        expect: "4/1,2,3,4",
        ..PLAIN
    },
    Property {
        name: "rule_disabled",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE RULE skip AS ON INSERT TO {s}.{t} DO INSTEAD NOTHING;
              ALTER TABLE {s}.{t} DISABLE RULE skip",
        ..PLAIN
    },
    Property {
        name: "view_auto",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE VIEW {s}.{t}_v AS SELECT id, v FROM {s}.{t}",
        target: "{t}_v",
        fallback: Some(RowFallback::View),
        ..PLAIN
    },
    Property {
        name: "view_instead_of",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE VIEW {s}.{t}_v AS SELECT id, v FROM {s}.{t};
              CREATE FUNCTION {s}.{t}_f() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN INSERT INTO {s}.{t} VALUES (NEW.id + 1000, NEW.v); RETURN NEW; END $$;
              CREATE TRIGGER put INSTEAD OF INSERT ON {s}.{t}_v
              FOR EACH ROW EXECUTE FUNCTION {s}.{t}_f()",
        target: "{t}_v",
        fallback: Some(RowFallback::View),
        expect: "1001:a,1002:b,1003:c,1004:d",
        ..PLAIN
    },
    Property {
        name: "view_not_insertable",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE VIEW {s}.{t}_v AS
              SELECT pg_catalog.count(*)::int4 AS id, pg_catalog.max(v) AS v FROM {s}.{t}",
        target: "{t}_v",
        fallback: Some(RowFallback::View),
        outcome: Outcome::Sqlstate("55000"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "view_check_option",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE VIEW {s}.{t}_v AS SELECT id, v FROM {s}.{t} WHERE id < 4
              WITH CHECK OPTION",
        target: "{t}_v",
        fallback: Some(RowFallback::View),
        outcome: Outcome::Sqlstate("44000"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "materialized_view",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE MATERIALIZED VIEW {s}.{t}_v AS SELECT id, v FROM {s}.{t}",
        target: "{t}_v",
        fallback: Some(RowFallback::View),
        outcome: Outcome::Sqlstate("42809"),
        expect: "",
        ..PLAIN
    },
];

const TRIGGERS: [Property; 2] = [
    Property {
        name: "row_triggers",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text); CREATE TABLE {s}.{t}_audit (id int4);
              CREATE FUNCTION {s}.{t}_b() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN IF NEW.id = 2 THEN RETURN NULL; END IF;
              NEW.v := NEW.v || '!'; RETURN NEW; END $$;
              CREATE FUNCTION {s}.{t}_a() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN INSERT INTO {s}.{t}_audit VALUES (NEW.id); RETURN NULL; END $$;
              CREATE TRIGGER b BEFORE INSERT ON {s}.{t}
              FOR EACH ROW EXECUTE FUNCTION {s}.{t}_b();
              CREATE TRIGGER a AFTER INSERT ON {s}.{t}
              FOR EACH ROW EXECUTE FUNCTION {s}.{t}_a()",
        outcome: Outcome::Rows(3),
        signature: "SELECT (SELECT pg_catalog.string_agg(id || ':' || v, ',' ORDER BY id)
                    FROM {s}.{t}) || '/' ||
                    (SELECT pg_catalog.string_agg(id::text, ',' ORDER BY id) FROM {s}.{t}_audit)",
        expect: "1:a!,3:c!,4:d!/1,3,4",
        ..PLAIN
    },
    Property {
        name: "statement_trigger_disabled",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text); CREATE TABLE {s}.{t}_audit (id int4);
              CREATE FUNCTION {s}.{t}_a() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN INSERT INTO {s}.{t}_audit VALUES (0); RETURN NULL; END $$;
              CREATE TRIGGER a AFTER INSERT ON {s}.{t}
              FOR EACH STATEMENT EXECUTE FUNCTION {s}.{t}_a();
              ALTER TABLE {s}.{t} DISABLE TRIGGER a",
        signature: "SELECT (SELECT pg_catalog.count(*) FROM {s}.{t}) || '/' ||
                    (SELECT pg_catalog.count(*) FROM {s}.{t}_audit)",
        expect: "4/0",
        ..PLAIN
    },
];

const KINDS_AND_CONSTRAINTS: [Property; 7] = [
    Property {
        name: "partitioned",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text) PARTITION BY RANGE (id);
              CREATE TABLE {s}.{t}_low PARTITION OF {s}.{t} FOR VALUES FROM (0) TO (3);
              CREATE TABLE {s}.{t}_high PARTITION OF {s}.{t} FOR VALUES FROM (3) TO (9)",
        signature: "SELECT (SELECT pg_catalog.count(*) FROM {s}.{t}_low) || '+' ||
                    (SELECT pg_catalog.count(*) FROM {s}.{t}_high)",
        expect: "2+2",
        ..PLAIN
    },
    Property {
        name: "no_partition_for_a_row",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text) PARTITION BY RANGE (id);
              CREATE TABLE {s}.{t}_low PARTITION OF {s}.{t} FOR VALUES FROM (0) TO (3)",
        outcome: Outcome::Sqlstate("23514"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "inheritance_child",
        ddl: "CREATE TABLE {s}.{t}_p (id int4, v text);
              CREATE TABLE {s}.{t} (n int4 DEFAULT 7) INHERITS ({s}.{t}_p)",
        signature: "SELECT (SELECT pg_catalog.string_agg(id || v || n, ',' ORDER BY id)
                    FROM {s}.{t}) || '/' || (SELECT pg_catalog.count(*) FROM ONLY {s}.{t}_p)",
        expect: "1a7,2b7,3c7,4d7/0",
        ..PLAIN
    },
    Property {
        name: "inheritance_parent",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              CREATE TABLE {s}.{t}_c (n int4 DEFAULT 7) INHERITS ({s}.{t})",
        signature: "SELECT (SELECT pg_catalog.count(*) FROM ONLY {s}.{t}) || '/' ||
                    (SELECT pg_catalog.count(*) FROM {s}.{t}_c)",
        expect: "4/0",
        ..PLAIN
    },
    Property {
        name: "unlogged",
        ddl: "CREATE UNLOGGED TABLE {s}.{t} (id int4, v text)",
        ..PLAIN
    },
    Property {
        name: "exclusion",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text, EXCLUDE USING btree (v WITH =))",
        batch: twin_v,
        outcome: Outcome::Sqlstate("23P01"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "deferred_foreign_key",
        ddl: "CREATE TABLE {s}.{t}_p (id int4 PRIMARY KEY);
              INSERT INTO {s}.{t}_p VALUES (1), (2), (3);
              CREATE TABLE {s}.{t} (id int4 REFERENCES {s}.{t}_p
              DEFERRABLE INITIALLY DEFERRED, v text)",
        outcome: Outcome::Sqlstate("23503"),
        expect: "",
        ..PLAIN
    },
];

const POLICIES: [Property; 6] = [
    Property {
        name: "row_security_passes",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              ALTER TABLE {s}.{t} ENABLE ROW LEVEL SECURITY;
              CREATE POLICY put ON {s}.{t} FOR INSERT WITH CHECK (id < 4);
              CREATE POLICY get ON {s}.{t} FOR SELECT USING (true);
              GRANT SELECT, INSERT ON {s}.{t} TO {x}",
        batch: three,
        fallback: Some(RowFallback::RowSecurity),
        outcome: Outcome::Rows(3),
        expect: "1:a,2:b,3:c",
        ..PLAIN
    },
    Property {
        name: "row_security_refuses",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text);
              ALTER TABLE {s}.{t} ENABLE ROW LEVEL SECURITY;
              CREATE POLICY put ON {s}.{t} FOR INSERT WITH CHECK (id < 4);
              CREATE POLICY get ON {s}.{t} FOR SELECT USING (true);
              GRANT SELECT, INSERT ON {s}.{t} TO {x}",
        fallback: Some(RowFallback::RowSecurity),
        outcome: Outcome::Sqlstate("42501"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "sequence_without_usage",
        ddl: "CREATE SEQUENCE {s}.{t}_q;
              CREATE TABLE {s}.{t} (id int4, v text DEFAULT pg_catalog.nextval('{s}.{t}_q')::text);
              GRANT SELECT, INSERT ON {s}.{t} TO {x}",
        columns: &["id"],
        batch: only_ids,
        outcome: Outcome::Sqlstate("42501"),
        expect: "",
        ..PLAIN
    },
    Property {
        name: "column_grant_covers_the_write",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text DEFAULT 'kept');
              GRANT SELECT, INSERT (id) ON {s}.{t} TO {x}",
        columns: &["id"],
        batch: only_ids,
        expect: "1:kept,2:kept,3:kept,4:kept",
        ..PLAIN
    },
    Property {
        name: "column_grant_misses_a_column",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text DEFAULT 'kept');
              GRANT SELECT, INSERT (id) ON {s}.{t} TO {x}",
        outcome: Outcome::Denied,
        expect: "",
        ..PLAIN
    },
    Property {
        name: "no_insert_grant",
        ddl: "CREATE TABLE {s}.{t} (id int4, v text); GRANT SELECT ON {s}.{t} TO {x}",
        outcome: Outcome::Denied,
        expect: "",
        ..PLAIN
    },
];

const FOREIGN: [Property; 2] = [
    Property {
        name: "foreign_table",
        ddl: "CREATE TABLE {s}.{t}_far (id int4, v text);
              CREATE TABLE {s}.{t}_audit (id int4);
              CREATE TABLE {s}.{t}_stmt (fired text);
              CREATE FUNCTION {s}.{t}_r() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN INSERT INTO {s}.{t}_audit VALUES (NEW.id); RETURN NEW; END $$;
              CREATE FUNCTION {s}.{t}_s() RETURNS trigger LANGUAGE plpgsql AS
              $$ BEGIN INSERT INTO {s}.{t}_stmt VALUES ('s'); RETURN NULL; END $$;
              CREATE TRIGGER r AFTER INSERT ON {s}.{t}_far
              FOR EACH ROW EXECUTE FUNCTION {s}.{t}_r();
              CREATE TRIGGER s AFTER INSERT ON {s}.{t}_far
              FOR EACH STATEMENT EXECUTE FUNCTION {s}.{t}_s();
              CREATE FOREIGN TABLE {s}.{t} (id int4, v text) SERVER {x}
              OPTIONS (schema_name '{s}', table_name '{t}_far')",
        signature: "SELECT (SELECT pg_catalog.string_agg(id || ':' || v, ',' ORDER BY id)
                    FROM {s}.{t}_far) || '/' ||
                    (SELECT pg_catalog.string_agg(id::text, ',' ORDER BY id)
                    FROM {s}.{t}_audit) || '/' ||
                    (SELECT pg_catalog.count(*) FROM {s}.{t}_stmt)",
        expect: "1:a,2:b,3:c,4:d/1,2,3,4/4",
        ..PLAIN
    },
    Property {
        name: "foreign_partition",
        ddl: "CREATE TABLE {s}.{t}_far (id int4, v text);
              CREATE TABLE {s}.{t} (id int4, v text) PARTITION BY RANGE (id);
              CREATE FOREIGN TABLE {s}.{t}_leaf PARTITION OF {s}.{t}
              FOR VALUES FROM (0) TO (9) SERVER {x}
              OPTIONS (schema_name '{s}', table_name '{t}_far')",
        fallback: Some(RowFallback::ForeignTable),
        signature: "SELECT pg_catalog.string_agg(id || ':' || v, ',' ORDER BY id) FROM {s}.{t}_far",
        ..PLAIN
    },
];

const FILE_WRAPPER: [Property; 1] = [Property {
    name: "file_table",
    ddl: "CREATE FOREIGN TABLE {s}.{t} (id int4, v text) SERVER {x}
          OPTIONS (filename '/tmp/{s}_file.csv', format 'csv')",
    fallback: Some(RowFallback::ForeignTable),
    outcome: Outcome::Sqlstate("0A000"),
    signature: "SELECT 'refused'",
    expect: "refused",
    ..PLAIN
}];

type Written = (bool, Option<RowFallback>, Result<WriteReport, ConnectError>);

async fn put(
    store: &Store,
    request: WriteRequest,
    requested: WritePath,
    batch: &RecordBatch,
) -> Written {
    let mut writer = match request.open(store.pool(), requested, store.options).await {
        Ok(writer) => writer,
        Err(error) => return (false, None, Err(error)),
    };
    let fallback = writer.fallback();
    let outcome = match writer.write(batch).await {
        Ok(()) => writer.commit().await,
        Err(error) => Err(error),
    };
    (true, fallback, outcome)
}

fn judge(property: &Property, requested: WritePath, relation: &QualifiedRelation, got: Written) {
    let name = property.name;
    let (opened, fallback, outcome) = got;
    let refused = |refusal| Err(ConnectError::WriteRefused { refusal });
    let column = |column: &str| column.to_string();
    let expected_fallback = match requested {
        WritePath::Bulk if opened => property.fallback,
        _ => None,
    };
    assert_eq!(fallback, expected_fallback, "{name} {requested:?}");
    let path = match (requested, property.fallback) {
        (WritePath::Bulk, None) => WritePath::Bulk,
        _ => WritePath::Row,
    };
    match property.outcome {
        Outcome::Rows(rows) => {
            assert_eq!(
                outcome,
                Ok(WriteReport { path, rows }),
                "{name} {requested:?}"
            );
        }
        Outcome::Sqlstate(expected) => match outcome {
            Err(ConnectError::Server { sqlstate, .. }) => {
                assert_eq!(sqlstate, expected, "{name} {requested:?}");
            }
            other => panic!("{name} {requested:?}: expected {expected}, got {other:?}"),
        },
        Outcome::Identity(name) => {
            let column = column(name);
            assert_eq!(outcome, refused(WriteRefusal::IdentityAlways { column }));
        }
        Outcome::Generated(name) => {
            let column = column(name);
            assert_eq!(outcome, refused(WriteRefusal::GeneratedColumn { column }));
        }
        Outcome::Denied => {
            let (relation, privilege) = (relation.clone(), Privilege::Insert);
            let denied = ConnectError::PermissionDenied {
                relation,
                privilege,
            };
            assert_eq!(outcome, Err(denied), "{name} {requested:?}");
        }
    }
}

async fn measure(cell: &Cell, owner: &Store, writer: &Store, extra: &str, property: &Property) {
    let mut signatures = Vec::new();
    for (requested, twin) in [(WritePath::Bulk, "b"), (WritePath::Row, "r")] {
        let table = format!("{}_{twin}", property.name);
        let fill = |template: &str| {
            template
                .replace("{s}", &cell.schema)
                .replace("{t}", &table)
                .replace("{x}", extra)
        };
        cell.sql(&fill(property.ddl)).await;
        let target = fill(property.target);
        let resolved = owner.target(cell, &target).await;
        let indexes: Vec<usize> = property
            .columns
            .iter()
            .map(|name| {
                let found = resolved
                    .columns
                    .iter()
                    .position(|c| c.name.as_str() == *name);
                found.expect("a column of the target")
            })
            .collect();
        let request = WriteRequest::new(&resolved)
            .expect("a relation takes rows")
            .columns(&indexes)
            .expect("the named columns");
        let relation = request.relation().clone();
        let got = put(writer, request, requested, &(property.batch)()).await;
        judge(property, requested, &relation, got);
        let signature = fill(property.signature);
        let row = cell.admin.query_one(signature.as_str(), &[]).await;
        let seen: Option<String> = row.expect(&signature).get(0);
        signatures.push(seen.unwrap_or_default());
    }
    assert_eq!(
        signatures[0], signatures[1],
        "{}: the twins differ",
        property.name
    );
    assert_eq!(signatures[0], property.expect, "{}", property.name);
}

async fn measure_all(properties: &[Property]) {
    let cell = Cell::open().await;
    let store = Store::new(&cell.settings(&[]));
    for property in properties {
        measure(&cell, &store, &store, "", property).await;
    }
    drop(store);
    no_backend_remains(&cell).await;
    cell.close().await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn identity_generated_and_default_columns_agree_or_refuse_on_both_paths() {
    measure_all(&COLUMNS).await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn rules_and_views_take_the_row_path_and_leave_the_same_tables() {
    measure_all(&RULES_AND_VIEWS).await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn row_triggers_and_disabled_statement_triggers_stay_on_the_bulk_path() {
    measure_all(&TRIGGERS).await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn bulk_and_row_leave_the_same_target_rows_under_a_statement_trigger() {
    let cell = Cell::open().await;
    let schema = &cell.schema;
    let store = Store::new(&cell.settings(&[]));
    let mut targets = Vec::new();
    for (requested, twin) in [(WritePath::Bulk, "b"), (WritePath::Row, "r")] {
        cell.sql(&format!(
            "CREATE TABLE {schema}.trig_{twin} (id int4, v text);
             CREATE TABLE {schema}.audit_{twin} (seq bigserial, fired text);
             CREATE TABLE {schema}.seen_{twin} (seq bigserial, n bigint, ids text);
             CREATE FUNCTION {schema}.before_{twin}() RETURNS trigger LANGUAGE plpgsql AS
             $$ BEGIN INSERT INTO {schema}.audit_{twin} (fired) VALUES ('before');
             RETURN NULL; END $$;
             CREATE FUNCTION {schema}.after_{twin}() RETURNS trigger LANGUAGE plpgsql AS
             $$ BEGIN INSERT INTO {schema}.audit_{twin} (fired) VALUES ('after');
             RETURN NULL; END $$;
             CREATE FUNCTION {schema}.trans_{twin}() RETURNS trigger LANGUAGE plpgsql AS
             $$ BEGIN INSERT INTO {schema}.seen_{twin} (n, ids) SELECT count(*),
             pg_catalog.string_agg(n.id::text, ',' ORDER BY n.id) FROM n;
             RETURN NULL; END $$;
             CREATE TRIGGER b BEFORE INSERT ON {schema}.trig_{twin}
             FOR EACH STATEMENT EXECUTE FUNCTION {schema}.before_{twin}();
             CREATE TRIGGER a AFTER INSERT ON {schema}.trig_{twin}
             FOR EACH STATEMENT EXECUTE FUNCTION {schema}.after_{twin}();
             CREATE TRIGGER t AFTER INSERT ON {schema}.trig_{twin}
             REFERENCING NEW TABLE AS n FOR EACH STATEMENT
             EXECUTE FUNCTION {schema}.trans_{twin}()"
        ))
        .await;
        let table = format!("trig_{twin}");
        let resolved = store.target(&cell, &table).await;
        let request = WriteRequest::new(&resolved).expect("a relation takes rows");
        let (opened, fallback, outcome) = put(&store, request, requested, &four()).await;
        assert!(opened, "{requested:?}");
        assert_eq!(fallback, None, "{requested:?}");
        let path = requested;
        assert_eq!(outcome, Ok(WriteReport { path, rows: 4 }), "{requested:?}");
        let target = format!(
            "SELECT pg_catalog.string_agg(id || ':' || v, ',' ORDER BY id) \
             FROM {schema}.trig_{twin}"
        );
        let row = cell
            .admin
            .query_one(target.as_str(), &[])
            .await
            .expect(&target);
        let seen: Option<String> = row.get(0);
        targets.push(seen.unwrap_or_default());
        let audit = format!(
            "SELECT pg_catalog.string_agg(fired, ',' ORDER BY seq) FROM {schema}.audit_{twin}"
        );
        let row = cell
            .admin
            .query_one(audit.as_str(), &[])
            .await
            .expect(&audit);
        let firings: Option<String> = row.get(0);
        let transitions = format!(
            "SELECT pg_catalog.string_agg(n::text || ':' || ids, ',' ORDER BY seq) \
             FROM {schema}.seen_{twin}"
        );
        let row = cell
            .admin
            .query_one(transitions.as_str(), &[])
            .await
            .expect(&transitions);
        let counts: Option<String> = row.get(0);
        match requested {
            WritePath::Bulk => {
                assert_eq!(firings.as_deref(), Some("before,after"), "bulk");
                assert_eq!(counts.as_deref(), Some("4:1,2,3,4"), "bulk");
            }
            WritePath::Row => {
                assert_eq!(firings.as_deref(), Some("before,after"), "row");
                assert_eq!(counts.as_deref(), Some("4:1,2,3,4"), "row");
            }
        }
    }
    assert_eq!(targets[0], targets[1], "the twins store the same rows");
    assert_eq!(targets[0], FOUR, "the stored rows");
    drop(store);
    no_backend_remains(&cell).await;
    cell.close().await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn row_path_sends_full_groups_plus_one_remainder_statement() {
    let cell = Cell::open().await;
    let schema = &cell.schema;
    let store = Store::new(&cell.settings(&[]));
    cell.sql(&format!(
        "CREATE TABLE {schema}.trig (id int4, v text);
         CREATE TABLE {schema}.audit (seq bigserial, fired text);
         CREATE TABLE {schema}.seen (seq bigserial, n bigint);
         CREATE FUNCTION {schema}.before() RETURNS trigger LANGUAGE plpgsql AS
         $$ BEGIN INSERT INTO {schema}.audit (fired) VALUES ('before');
         RETURN NULL; END $$;
         CREATE FUNCTION {schema}.after() RETURNS trigger LANGUAGE plpgsql AS
         $$ BEGIN INSERT INTO {schema}.audit (fired) VALUES ('after');
         RETURN NULL; END $$;
         CREATE FUNCTION {schema}.trans() RETURNS trigger LANGUAGE plpgsql AS
         $$ BEGIN INSERT INTO {schema}.seen (n) SELECT count(*) FROM n;
         RETURN NULL; END $$;
         CREATE TRIGGER b BEFORE INSERT ON {schema}.trig
         FOR EACH STATEMENT EXECUTE FUNCTION {schema}.before();
         CREATE TRIGGER a AFTER INSERT ON {schema}.trig
         FOR EACH STATEMENT EXECUTE FUNCTION {schema}.after();
         CREATE TRIGGER t AFTER INSERT ON {schema}.trig
         REFERENCING NEW TABLE AS n FOR EACH STATEMENT
         EXECUTE FUNCTION {schema}.trans()"
    ))
    .await;
    let resolved = store.target(&cell, "trig").await;
    let request = WriteRequest::new(&resolved).expect("a relation takes rows");
    let batch = batch_of(&[
        ("id", ids(1..601)),
        (
            "v",
            Arc::new(StringArray::from(
                (1..601).map(|id| format!("r{id}")).collect::<Vec<_>>(),
            )),
        ),
    ]);
    let (opened, fallback, outcome) = put(&store, request, WritePath::Row, &batch).await;
    assert!(opened);
    assert_eq!(fallback, None);
    assert_eq!(
        outcome,
        Ok(WriteReport {
            path: WritePath::Row,
            rows: 600
        })
    );
    let audit =
        format!("SELECT pg_catalog.string_agg(fired, ',' ORDER BY seq) FROM {schema}.audit");
    let row = cell
        .admin
        .query_one(audit.as_str(), &[])
        .await
        .expect(&audit);
    let firings: Option<String> = row.get(0);
    assert_eq!(
        firings.as_deref(),
        Some("before,after,before,after,before,after")
    );
    let transitions =
        format!("SELECT pg_catalog.string_agg(n::text, ',' ORDER BY seq) FROM {schema}.seen");
    let row = cell
        .admin
        .query_one(transitions.as_str(), &[])
        .await
        .expect(&transitions);
    let counts: Option<String> = row.get(0);
    assert_eq!(counts.as_deref(), Some("256,256,88"));
    drop(store);
    no_backend_remains(&cell).await;
    cell.close().await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn partitions_inheritance_persistence_and_constraints_agree_on_both_paths() {
    measure_all(&KINDS_AND_CONSTRAINTS).await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn row_security_and_grants_are_judged_the_same_on_both_paths() {
    let cell = Cell::open().await;
    let schema = &cell.schema;
    let role = format!("p_{}", &schema[3..]);
    let password = format!("p{}{}", tag(), tag());
    cell.sql(&format!(
        "CREATE ROLE {role} LOGIN PASSWORD '{password}'; GRANT USAGE ON SCHEMA {schema} TO {role}"
    ))
    .await;
    let base = url();
    let (_, endpoint) = base.split_once('@').expect("a URL with userinfo");
    let restricted = format!("postgresql://{role}:{password}@{endpoint}");
    let owner = Store::new(&cell.settings(&[]));
    let writer = Store::new(&cell.settings(&[("url", restricted.as_str())]));
    for property in &POLICIES {
        measure(&cell, &owner, &writer, &role, property).await;
    }
    let as_owner = Property {
        name: "row_security_spares_the_owner",
        fallback: None,
        outcome: Outcome::Rows(4),
        expect: FOUR,
        ..POLICIES[1]
    };
    measure(&cell, &owner, &owner, &role, &as_owner).await;
    let sql = format!("SELECT count(*) FROM {schema}.row_security_refuses_b");
    assert_eq!(cell.count(&sql).await, 0);
    let relation = owner.target(&cell, "row_security_refuses_r").await;
    let request = WriteRequest::new(&relation).expect("a relation takes rows");
    let (_, _, refused) = put(&writer, request, WritePath::Row, &four()).await;
    let text = refused.expect_err("the policy refuses id 4").to_string();
    assert!(text.contains("row-level security policy"), "{text}");
    assert!(!text.contains("INSERT privilege"), "{text}");
    let relation = owner.target(&cell, "sequence_without_usage_b").await;
    let request = WriteRequest::new(&relation)
        .expect("a relation takes rows")
        .columns(&[0])
        .expect("the id column");
    let (_, _, refused) = put(&writer, request, WritePath::Bulk, &only_ids()).await;
    let text = refused.expect_err("no USAGE on the sequence").to_string();
    assert!(text.contains("sequence"), "{text}");
    assert!(!text.contains("INSERT privilege"), "{text}");
    drop((owner, writer));
    no_backend_remains(&cell).await;
    cell.sql(&format!(
        "DROP OWNED BY {role}; DROP SCHEMA {schema} CASCADE; DROP ROLE {role}"
    ))
    .await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn a_postgres_fdw_table_takes_the_bulk_path_and_other_wrappers_do_not() {
    let cell = Cell::open().await;
    let server = format!("far_{}", &cell.schema[3..]);
    let files = format!("fil_{}", &cell.schema[3..]);
    let base = url();
    let (userinfo, endpoint) = base.split_once('@').expect("a URL with userinfo");
    let (user, password) = userinfo
        .rsplit_once("//")
        .and_then(|(_, pair)| pair.split_once(':'))
        .expect("a user and a password");
    let database = endpoint.rsplit_once('/').expect("a database").1;
    cell.sql(&format!(
        "CREATE EXTENSION IF NOT EXISTS postgres_fdw;
         CREATE EXTENSION IF NOT EXISTS file_fdw;
         CREATE SERVER {server} FOREIGN DATA WRAPPER postgres_fdw
         OPTIONS (host '127.0.0.1', port '5432', dbname '{database}');
         CREATE USER MAPPING FOR PUBLIC SERVER {server}
         OPTIONS (user '{user}', password '{password}');
         CREATE SERVER {files} FOREIGN DATA WRAPPER file_fdw"
    ))
    .await;
    let store = Store::new(&cell.settings(&[]));
    for property in &FOREIGN {
        measure(&cell, &store, &store, &server, property).await;
    }
    for property in &FILE_WRAPPER {
        measure(&cell, &store, &store, &files, property).await;
    }
    drop(store);
    no_backend_remains(&cell).await;
    let schema = &cell.schema;
    cell.sql(&format!(
        "DROP SCHEMA {schema} CASCADE; DROP SERVER {server} CASCADE; DROP SERVER {files} CASCADE"
    ))
    .await;
}

#[tokio::test]
#[ignore = "live: make pg-up, REPARK_PG_URL"]
async fn another_sessions_temporary_table_is_refused_the_same_on_both_paths() {
    let cell = Cell::open().await;
    cell.sql("CREATE TEMP TABLE c4_temp (id int4, v text)")
        .await;
    let row = cell
        .admin
        .query_one(
            "SELECT pg_catalog.pg_my_temp_schema()::regnamespace::text",
            &[],
        )
        .await
        .expect("the session's temporary schema");
    let schema: String = row.get(0);
    let relation = QualifiedRelation::new(
        PgIdent::new(schema).expect("schema"),
        PgIdent::new("c4_temp").expect("table"),
    );
    let store = Store::new(&cell.settings(&[]));
    let resolved = store
        .reader
        .resolve(ScanSource::Relation(relation))
        .await
        .expect(LIVE);
    for requested in [WritePath::Bulk, WritePath::Row] {
        let request = WriteRequest::new(&resolved).expect("a relation takes rows");
        let (_, fallback, outcome) = put(&store, request, requested, &four()).await;
        assert_eq!(fallback, None, "{requested:?}");
        match outcome {
            Err(ConnectError::Server { sqlstate, .. }) => assert_eq!(sqlstate, "0A000"),
            other => panic!("{requested:?}: expected 0A000, got {other:?}"),
        }
    }
    assert_eq!(cell.count("SELECT count(*) FROM c4_temp").await, 0);
    drop(store);
    no_backend_remains(&cell).await;
    cell.close().await;
}
