"""V3-COV measured matrix — the verdict per program, and the two engine halves it joins.

pins: v3-cov-statement-coverage/C-003
"""

from __future__ import annotations

from _v3_statement_coverage_repark import REPARK
from _v3_statement_coverage_spark import SPARK

VERDICTS: dict[str, str] = {
    "create-v3-flat": "EQUAL",
    "create-v3-partitioned": "EQUAL",
    "create-v3-bucket-transform": "EQUAL",
    "create-v3-write-order": "REFUSED",
    "create-v3-properties": "EQUAL",
    "ctas-v3": "EQUAL",
    "insert-into": "EQUAL",
    "insert-into-select": "EQUAL",
    "insert-overwrite-table": "EQUAL",
    "insert-overwrite-partition-static-values": "EQUAL",
    "insert-overwrite-partition-static-select": "EQUAL",
    "insert-overwrite-partition-dynamic": "DIVERGES",
    "delete-where-mor": "EQUAL",
    "delete-where-cow": "EQUAL",
    "delete-where-partitioned-mor": "EQUAL",
    "delete-where-partitioned-cow": "EQUAL",
    "delete-in-subquery-mor": "EQUAL",
    "delete-not-in-subquery-mor": "EQUAL",
    "delete-exists-subquery-mor": "EQUAL",
    "delete-not-exists-subquery-mor": "EQUAL",
    "delete-in-subquery-cow": "EQUAL",
    "delete-all-rows-mor": "DIVERGES",
    "update-where-mor": "EQUAL",
    "update-where-cow": "EQUAL",
    "update-where-partitioned-mor": "EQUAL",
    "update-in-subquery-mor": "EQUAL",
    "update-not-in-subquery-mor": "DIVERGES",
    "update-exists-subquery-mor": "DIVERGES",
    "update-partition-key-cow": "EQUAL",
    "merge-matched-update-mor": "EQUAL",
    "merge-matched-update-cow": "EQUAL",
    "merge-matched-delete-mor": "EQUAL",
    "merge-matched-delete-cow": "EQUAL",
    "merge-not-matched-insert": "EQUAL",
    "merge-not-matched-by-source-delete": "EQUAL",
    "merge-not-matched-by-source-update": "EQUAL",
    "merge-mixed-arms": "EQUAL",
    "merge-matched-conditional": "EQUAL",
    "merge-partitioned-mor": "EQUAL",
    "merge-source-table-mor": "EQUAL",
    "alter-add-column": "EQUAL",
    "alter-drop-column": "EQUAL",
    "alter-rename-column": "EQUAL",
    "alter-alter-column-type": "EQUAL",
    "alter-add-partition-field": "EQUAL",
    "alter-drop-partition-field": "EQUAL",
    "alter-add-column-partitioned": "EQUAL",
    "alter-set-tblproperties": "EQUAL",
    "alter-unset-tblproperties": "EQUAL",
    "alter-write-ordered-by": "DIVERGES",
    "alter-set-format-version-3": "EQUAL",
    "alter-set-format-version-3-mor": "EQUAL",
    "truncate-table": "EQUAL",
    "drop-table": "EQUAL",
    "meta-snapshots": "EQUAL",
    "meta-files": "EQUAL",
    "meta-delete-files": "EQUAL",
    "meta-manifests": "EQUAL",
    "meta-history": "EQUAL",
    "meta-refs": "EQUAL",
    "meta-partitions": "EQUAL",
    "meta-entries": "EQUAL",
    "meta-all-data-files": "EQUAL",
    "meta-position-deletes": "DIVERGES",
    "lineage-projection": "EQUAL",
    "time-travel-version-as-of": "EQUAL",
    "time-travel-timestamp-as-of": "EQUAL",
    "branch-create-and-read": "EQUAL",
    "branch-write": "EQUAL",
    "branch-replace-and-drop": "EQUAL",
    "tag-create-and-read": "EQUAL",
    "tag-retention": "EQUAL",
    "branch-retention": "EQUAL",
    "call-expire-snapshots": "EQUAL",
    "call-remove-orphan-files": "EQUAL",
    "call-rewrite-data-files": "EQUAL",
    "call-rewrite-manifests": "EQUAL",
    "call-rewrite-position-delete-files": "DIVERGES",
    "call-rollback-to-snapshot": "EQUAL",
    "call-register-table": "EQUAL",
}

__all__ = ["REPARK", "SPARK", "VERDICTS"]
