"""FN-SPLIT identity: ``functions.__all__`` is unchanged and every name resolves.

Relocation discipline (docs/testing.md): this is a declared move-only split. The 207-name
``__all__`` tuple is the before==after pin. Adding a new function is a later FN-A..F PR,
not this file's job.
"""

from __future__ import annotations

from repark.spark import functions as F  # noqa: N812 — PySpark idiom

# Frozen 2026-08-14 on 8b5c8cb before the split. Do not edit unless a later batch
# deliberately grows the surface (and then this pin moves with that batch).
_PRE_SPLIT_ALL: tuple[str, ...] = (
    "PandasUDFType",
    "PythonUDFColumn",
    "UserDefinedFunction",
    "UserDefinedTableFunction",
    "abs",
    "acos",
    "acosh",
    "add_months",
    "approx_percentile",
    "array",
    "array_contains",
    "array_distinct",
    "array_except",
    "array_intersect",
    "array_join",
    "array_max",
    "array_min",
    "array_position",
    "array_remove",
    "array_repeat",
    "array_sort",
    "array_union",
    "arrays_zip",
    "ascii",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "avg",
    "base64",
    "bit_and",
    "bit_or",
    "bit_xor",
    "bucket",
    "ceil",
    "ceiling",
    "chr",
    "coalesce",
    "col",
    "collect_list",
    "collect_set",
    "concat",
    "concat_ws",
    "corr",
    "cos",
    "cosh",
    "cot",
    "count",
    "countDistinct",
    "count_distinct",
    "covar_pop",
    "covar_samp",
    "crc32",
    "csc",
    "currentDate",
    "currentTimestamp",
    "current_date",
    "current_timestamp",
    "date_add",
    "date_format",
    "date_part",
    "date_sub",
    "date_trunc",
    "datediff",
    "dayname",
    "dayofmonth",
    "dayofweek",
    "dayofyear",
    "days",
    "decode",
    "dense_rank",
    "elt",
    "encode",
    "exp",
    "explode",
    "explode_outer",
    "expr",
    "extract",
    "find_in_set",
    "first",
    "flatten",
    "floor",
    "format_number",
    "format_string",
    "from_csv",
    "from_unixtime",
    "from_utc_timestamp",
    "from_xml",
    "greatest",
    "hash",
    "hour",
    "hours",
    "hypot",
    "initcap",
    "input_file_name",
    "instr",
    "isnan",
    "isnull",
    "json_tuple",
    "kurtosis",
    "last",
    "last_day",
    "least",
    "length",
    "levenshtein",
    "lit",
    "locate",
    "log",
    "log10",
    "lower",
    "lpad",
    "ltrim",
    "make_timestamp",
    "map_entries",
    "map_from_arrays",
    "map_keys",
    "map_values",
    "max",
    "md5",
    "mean",
    "median",
    "min",
    "minute",
    "mode",
    "monotonically_increasing_id",
    "month",
    "monthname",
    "months",
    "months_between",
    "nanvl",
    "next_day",
    "ntile",
    "overlay",
    "pandas_udf",
    "percentile_approx",
    "posexplode",
    "posexplode_outer",
    "position",
    "pow",
    "power",
    "quarter",
    "raise_error",
    "rand",
    "randn",
    "random",
    "rank",
    "regexp_extract",
    "regexp_replace",
    "repeat",
    "reverse",
    "round",
    "row_number",
    "rpad",
    "rtrim",
    "schema_of_csv",
    "schema_of_json",
    "schema_of_xml",
    "sec",
    "second",
    "sentences",
    "sequence",
    "sha1",
    "sha2",
    "signum",
    "sin",
    "sinh",
    "size",
    "skewness",
    "slice",
    "sort_array",
    "soundex",
    "spark_partition_id",
    "split",
    "sqrt",
    "stddev",
    "stddev_pop",
    "stddev_samp",
    "struct",
    "substring_index",
    "sum",
    "tan",
    "tanh",
    "timestamp_micros",
    "timestamp_millis",
    "timestamp_seconds",
    "to_date",
    "to_timestamp",
    "to_utc_timestamp",
    "translate",
    "trim",
    "trunc",
    "try_to_timestamp",
    "udf",
    "udtf",
    "unbase64",
    "unix_timestamp",
    "upper",
    "var_pop",
    "var_samp",
    "variance",
    "weekday",
    "weekofyear",
    "when",
    "xxhash64",
    "year",
    "years",
)


def test_functions_all_matches_pre_split_inventory() -> None:
    assert tuple(F.__all__) == _PRE_SPLIT_ALL
    assert len(F.__all__) == 207


def test_every_all_name_resolves() -> None:
    missing = [name for name in F.__all__ if not hasattr(F, name)]
    assert missing == []
