HERE=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
ROOT=${COORDINATOR_ROOT:-/tmp/oc-worker}
LIB=${COORDINATOR_LIB:-$ROOT/_lib}
SCRATCH=${COORDINATOR_SCRATCH:-/tmp}
MERGE_QUEUE=${COORDINATOR_MERGE_QUEUE:-$ROOT/run16/merge-queue.txt}
GH_OWNER=${COORDINATOR_GH_OWNER:-TRO-Wolf}
