"""Spark-shaped parameter grids and cross-validation orchestration."""

from __future__ import annotations

import contextlib
import itertools
import math
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Any

from repark.errors import IllegalArgumentException, PySparkTypeError
from repark.spark._idents import quote_ident as _quote_ident
from repark.spark._temp_views import scratch_view_name
from repark.spark.ml.base import Estimator, Model, _require_repark_dataframe
from repark.spark.ml.evaluation import Evaluator
from repark.spark.ml.param import Param, TypeConverters


class ParamGridBuilder:
    """Build a Cartesian product of parameter maps."""

    def __init__(self) -> None:
        """Initialize an empty grid and base map."""
        self._grids: list[tuple[Param[Any], list[Any]]] = []
        self._base: dict[Param[Any], Any] = {}

    def baseOn(self, *args: Any) -> ParamGridBuilder:
        """Set base parameters from a mapping or alternating pairs."""
        if len(args) == 1 and isinstance(args[0], dict):
            for param, value in args[0].items():
                if not isinstance(param, Param):
                    raise PySparkTypeError(
                        f"ParamGridBuilder.baseOn keys must be Param, got {type(param).__name__}"
                    )
                self._base[param] = value
            return self
        if len(args) % 2 != 0:
            raise IllegalArgumentException(
                "ParamGridBuilder.baseOn expects a dict or even-length Param/value pairs"
            )
        for index in range(0, len(args), 2):
            param = args[index]
            value = args[index + 1]
            if not isinstance(param, Param):
                raise PySparkTypeError(
                    "ParamGridBuilder.baseOn expects Param at even index, "
                    f"got {type(param).__name__}"
                )
            self._base[param] = value
        return self

    def addGrid(self, param: Param[Any], values: list[Any] | tuple[Any, ...]) -> ParamGridBuilder:
        """Add a parameter axis of candidate values."""
        if not isinstance(param, Param):
            raise PySparkTypeError(
                f"ParamGridBuilder.addGrid param must be Param, got {type(param).__name__}"
            )
        if not isinstance(values, (list, tuple)):
            raise PySparkTypeError(
                f"ParamGridBuilder.addGrid values must be list/tuple, got {type(values).__name__}"
            )
        if len(values) == 0:
            raise IllegalArgumentException("ParamGridBuilder.addGrid values must be non-empty")
        self._grids.append((param, list(values)))
        return self

    def build(self) -> list[dict[Param[Any], Any]]:
        """Return the Cartesian product over the base map."""
        if not self._grids:
            return [dict(self._base)]
        axes = [grid[1] for grid in self._grids]
        params = [grid[0] for grid in self._grids]
        maps: list[dict[Param[Any], Any]] = []
        for combo in itertools.product(*axes):
            param_map = dict(self._base)
            for param, value in zip(params, combo, strict=True):
                param_map[param] = value
            maps.append(param_map)
        return maps


class CrossValidator(Estimator["CrossValidatorModel"]):
    """Select estimator parameters by deterministic K-fold validation."""

    def __init__(
        self,
        *,
        estimator: Estimator[Any] | None = None,
        estimatorParamMaps: list[dict[Param[Any], Any]] | None = None,  # noqa: N803
        evaluator: Evaluator | None = None,
        numFolds: int | None = None,  # noqa: N803
        seed: int | None = None,
        parallelism: int | None = None,
        collectSubModels: bool | None = None,  # noqa: N803
    ) -> None:
        """Initialize cross-validation parameters."""
        super().__init__()
        self.estimator: Param[Any] = Param(
            self, "estimator", "estimator to be cross-validated", TypeConverters.identity
        )
        self.estimatorParamMaps: Param[list[Any]] = Param(
            self,
            "estimatorParamMaps",
            "param maps generated by ParamGridBuilder",
            TypeConverters.identity,
        )
        self.evaluator: Param[Any] = Param(
            self, "evaluator", "evaluator used to select best model", TypeConverters.identity
        )
        self.numFolds: Param[int] = Param(
            self, "numFolds", "number of folds for cross validation", TypeConverters.toInt
        )
        self.seed: Param[int] = Param(self, "seed", "random seed", TypeConverters.toInt)
        self.parallelism: Param[int] = Param(
            self,
            "parallelism",
            "max worker threads for independent fold x paramMap fits (M6; 1 = sequential)",
            TypeConverters.toInt,
        )
        self.collectSubModels: Param[bool] = Param(
            self,
            "collectSubModels",
            "whether to collect submodels (accepted; not retained in v1)",
            TypeConverters.toBoolean,
        )
        self._setDefault(
            estimator=None,
            estimatorParamMaps=[],
            evaluator=None,
            numFolds=3,
            seed=0,
            parallelism=1,
            collectSubModels=False,
        )
        if estimator is not None:
            self.setEstimator(estimator)
        if estimatorParamMaps is not None:
            self.setEstimatorParamMaps(estimatorParamMaps)
        if evaluator is not None:
            self.setEvaluator(evaluator)
        if numFolds is not None:
            self.setNumFolds(numFolds)
        if seed is not None:
            self._set(seed=seed)
        if parallelism is not None:
            self.setParallelism(int(parallelism))
        if collectSubModels is not None:
            self._set(collectSubModels=collectSubModels)

    def setEstimator(self, value: Estimator[Any]) -> CrossValidator:
        """Set and validate the estimator."""
        if not isinstance(value, Estimator):
            raise PySparkTypeError(f"estimator must be Estimator, got {type(value).__name__}")
        return self._set(estimator=value)

    def getEstimator(self) -> Estimator[Any]:
        """Return the configured estimator."""
        value = self.getOrDefault(self.estimator)
        if value is None:
            raise IllegalArgumentException("CrossValidator.estimator is not set")
        return value  # type: ignore[no-any-return]

    def setEstimatorParamMaps(self, value: list[dict[Param[Any], Any]]) -> CrossValidator:
        """Set estimator parameter maps."""
        if not isinstance(value, list):
            raise PySparkTypeError(f"estimatorParamMaps must be list, got {type(value).__name__}")
        return self._set(estimatorParamMaps=list(value))

    def getEstimatorParamMaps(self) -> list[dict[Param[Any], Any]]:
        """Return estimator parameter maps."""
        return list(self.getOrDefault(self.estimatorParamMaps))  # type: ignore[no-any-return]

    def setEvaluator(self, value: Evaluator) -> CrossValidator:
        """Set and validate the evaluator."""
        if not isinstance(value, Evaluator):
            raise PySparkTypeError(f"evaluator must be Evaluator, got {type(value).__name__}")
        return self._set(evaluator=value)

    def getEvaluator(self) -> Evaluator:
        """Return the configured evaluator."""
        value = self.getOrDefault(self.evaluator)
        if value is None:
            raise IllegalArgumentException("CrossValidator.evaluator is not set")
        return value  # type: ignore[no-any-return]

    def setNumFolds(self, value: int) -> CrossValidator:
        """Set the number of folds, which must be at least two."""
        if int(value) < 2:
            raise IllegalArgumentException(f"numFolds must be >= 2, got {value}")
        return self._set(numFolds=int(value))

    def getNumFolds(self) -> int:
        """Return the number of folds."""
        return int(self.getOrDefault(self.numFolds))

    def setSeed(self, value: int) -> CrossValidator:
        """Set the fold assignment seed."""
        return self._set(seed=int(value))

    def getSeed(self) -> int:
        """Return the fold assignment seed."""
        return int(self.getOrDefault(self.seed))

    def _with_fold_column(self, frame: Any, num_folds: int, seed: int) -> tuple[Any, str, str]:
        """Assign deterministic fold labels and materialize them once.

        Materialization prevents lazy window re-evaluation from changing folds for unchanged
        input row order.
        """
        fold_col = f"__cv_fold_{uuid.uuid4().hex[:8]}"
        view = scratch_view_name(frame._session, "__repark_cv_src_")
        mat_view = scratch_view_name(frame._session, "__repark_cv_mat_")
        frame.createOrReplaceTempView(view)
        sql = (
            f"SELECT {view}.*, "
            f"MOD(abs(hash(concat(CAST(ROW_NUMBER() OVER (ORDER BY 1) AS VARCHAR), "
            f"'_', CAST({int(seed)} AS VARCHAR)))), {int(num_folds)}) AS \"{fold_col}\" "
            f"FROM {view}"
        )
        try:
            try:
                folded_lazy = frame._spawn(frame._session.sql(sql))
            except Exception:
                sql = (
                    f"SELECT {view}.*, "
                    f'MOD(ROW_NUMBER() OVER (ORDER BY 1) - 1, {int(num_folds)}) AS "{fold_col}" '
                    f"FROM {view}"
                )
                folded_lazy = frame._spawn(frame._session.sql(sql))
            frame._session.materialize_as_temp_view(mat_view, folded_lazy._inner)
            folded = frame._spawn(frame._session.sql(f"SELECT * FROM {mat_view}"))
        except Exception:
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(mat_view)
            raise
        finally:
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(view)
        return folded, fold_col, mat_view

    def getParallelism(self) -> int:
        """Return the maximum worker count."""
        return max(1, int(self.getOrDefault(self.parallelism)))

    def setParallelism(self, value: int) -> CrossValidator:
        """Set the worker count, which must be at least one."""
        if int(value) < 1:
            raise IllegalArgumentException(f"parallelism must be >= 1, got {value}")
        return self._set(parallelism=int(value))

    def _split_fold(
        self, frame: Any, folded: Any, fold_col: str, fold_index: int
    ) -> tuple[Any, Any, str]:
        """Return ``(train, test, train_view)`` for one fold."""
        quoted_fold = _quote_ident(fold_col)
        train_view = scratch_view_name(frame._session, "__repark_cv_tr_")
        folded.createOrReplaceTempView(train_view)
        try:
            train = frame._spawn(
                frame._session.sql(
                    f"SELECT * EXCLUDE ({quoted_fold}) FROM {train_view} "
                    f"WHERE {quoted_fold} <> {fold_index}"
                )
            )
        except Exception:
            cols = [name for name in folded.columns if name != fold_col]
            col_sql = ", ".join(_quote_ident(name) for name in cols)
            train = frame._spawn(
                frame._session.sql(
                    f"SELECT {col_sql} FROM {train_view} WHERE {quoted_fold} <> {fold_index}"
                )
            )
        try:
            test = frame._spawn(
                frame._session.sql(
                    f"SELECT * EXCLUDE ({quoted_fold}) FROM {train_view} "
                    f"WHERE {quoted_fold} = {fold_index}"
                )
            )
        except Exception:
            cols = [name for name in folded.columns if name != fold_col]
            col_sql = ", ".join(_quote_ident(name) for name in cols)
            test = frame._spawn(
                frame._session.sql(
                    f"SELECT {col_sql} FROM {train_view} WHERE {quoted_fold} = {fold_index}"
                )
            )
        return train, test, train_view

    @staticmethod
    def _eval_fold_param(
        estimator: Estimator[Any],
        evaluator: Evaluator,
        train: Any,
        test: Any,
        param_map: dict[Param[Any], Any],
        map_index: int,
        fold_index: int,
    ) -> tuple[int, int, float]:
        """Return ``(map_index, fold_index, score)`` for one map and fold."""
        model = estimator.fit(train, params=param_map if param_map else None)
        predictions = model.transform(test)
        score = float(evaluator.evaluate(predictions))
        if math.isnan(score):
            raise IllegalArgumentException(
                "CrossValidator.fit: fold evaluation returned NaN "
                f"(map_index={map_index}, fold_index={fold_index}); "
                "refuse silent bestModel selection (e.g. R2 on a "
                "zero-variance label fold)"
            )
        return map_index, fold_index, score

    def _fit(self, dataset: Any) -> CrossValidatorModel:
        """Search maps by fold metrics and refit the best map.

        Build and register fold views before worker fan-out. Reduce scores on the caller thread
        to avoid session races and concurrent floating-point accumulation.
        """
        frame = _require_repark_dataframe(dataset, verb="CrossValidator.fit")
        estimator = self.getEstimator()
        evaluator = self.getEvaluator()
        param_maps = self.getEstimatorParamMaps()
        if not param_maps:
            param_maps = [{}]
        num_folds = self.getNumFolds()
        seed = self.getSeed()
        parallelism = self.getParallelism()

        folded, fold_col, mat_view = self._with_fold_column(frame, num_folds, seed)

        metrics: list[float] = [0.0] * len(param_maps)
        train_views: list[str] = []
        try:
            fold_splits: list[tuple[int, Any, Any]] = []
            for fold_index in range(num_folds):
                train, test, train_view = self._split_fold(frame, folded, fold_col, fold_index)
                train_views.append(train_view)
                fold_splits.append((fold_index, train, test))

            jobs: list[tuple[int, int, Any, Any, dict[Param[Any], Any]]] = []
            for fold_index, train, test in fold_splits:
                for map_index, param_map in enumerate(param_maps):
                    jobs.append((map_index, fold_index, train, test, param_map))

            if parallelism <= 1 or len(jobs) <= 1:
                for map_index, fold_index, train, test, param_map in jobs:
                    _, _, score = self._eval_fold_param(
                        estimator, evaluator, train, test, param_map, map_index, fold_index
                    )
                    metrics[map_index] += score
            else:
                workers = min(parallelism, len(jobs))
                with ThreadPoolExecutor(max_workers=workers) as pool:
                    futures = [
                        pool.submit(
                            self._eval_fold_param,
                            estimator,
                            evaluator,
                            train,
                            test,
                            param_map,
                            map_index,
                            fold_index,
                        )
                        for map_index, fold_index, train, test, param_map in jobs
                    ]
                    fold_scores = [future.result() for future in as_completed(futures)]
                for map_index, _fold_index, score in fold_scores:
                    metrics[map_index] += score
        finally:
            for train_view in train_views:
                with contextlib.suppress(Exception):
                    frame._session.drop_temp_view(train_view)
            with contextlib.suppress(Exception):
                frame._session.drop_temp_view(mat_view)

        avg_metrics = [value / float(num_folds) for value in metrics]
        if any(math.isnan(value) for value in avg_metrics):
            raise IllegalArgumentException(
                "CrossValidator.fit: avgMetrics contains NaN; cannot select bestModel"
            )
        larger_better = bool(evaluator.isLargerBetter())
        if larger_better:
            best_index = max(range(len(avg_metrics)), key=lambda index: avg_metrics[index])
        else:
            best_index = min(range(len(avg_metrics)), key=lambda index: avg_metrics[index])
        best_map = param_maps[best_index]
        best_model = estimator.fit(frame, params=best_map if best_map else None)
        result = CrossValidatorModel(
            bestModel=best_model,
            avgMetrics=avg_metrics,
            estimator=estimator,
            evaluator=evaluator,
            estimatorParamMaps=param_maps,
            numFolds=num_folds,
        )
        result.uid = self.uid
        return result


class CrossValidatorModel(Model):
    """Fitted cross-validator exposing ``bestModel`` and ``avgMetrics``."""

    def __init__(
        self,
        *,
        bestModel: Model | None = None,  # noqa: N803
        avgMetrics: list[float] | None = None,  # noqa: N803
        estimator: Estimator[Any] | None = None,
        evaluator: Evaluator | None = None,
        estimatorParamMaps: list[dict[Param[Any], Any]] | None = None,  # noqa: N803
        numFolds: int = 3,  # noqa: N803
    ) -> None:
        """Initialize the best model and fold-averaged metrics."""
        super().__init__()
        self.bestModel = bestModel
        self.avgMetrics = list(avgMetrics or [])
        self.estimator = estimator
        self.evaluator = evaluator
        self.estimatorParamMaps = list(estimatorParamMaps or [])
        self.numFolds = int(numFolds)

    def _transform(self, dataset: Any) -> Any:
        """Transform with ``bestModel``."""
        if self.bestModel is None:
            raise IllegalArgumentException("CrossValidatorModel has no bestModel")
        return self.bestModel.transform(dataset)

    def copy(self, extra: dict[Any, Any] | None = None) -> CrossValidatorModel:
        """Copy the wrapper and apply overrides to ``bestModel``."""
        best = self.bestModel.copy(extra=extra) if self.bestModel is not None else None
        that = CrossValidatorModel(
            bestModel=best,
            avgMetrics=list(self.avgMetrics),
            estimator=self.estimator,
            evaluator=self.evaluator,
            estimatorParamMaps=list(self.estimatorParamMaps),
            numFolds=self.numFolds,
        )
        that.uid = self.uid
        return that


__all__ = [
    "CrossValidator",
    "CrossValidatorModel",
    "ParamGridBuilder",
]
