"""``repark.ml.feature`` — plan-built feature transformers (M2 R-ML-FEATURE + Q1).

Import paths mirror ``pyspark.ml.feature`` under ``repark.ml.feature`` only.
"""

from __future__ import annotations

from repark.ml.feature._transformers import (
    COUNT_VECTORIZER_STATUS,
    IDF,
    IDF_STATUS,
    # Quantile family / CV-IDF status exported for ledger/tests
    QUANTILE_FAMILY_STATUS,
    REGEX_TOKENIZER_GAPS_FALSE_STATUS,
    Binarizer,
    Bucketizer,
    CountVectorizer,
    CountVectorizerModel,
    IDFModel,
    Imputer,
    ImputerModel,
    IndexToString,
    MaxAbsScaler,
    MaxAbsScalerModel,
    MinMaxScaler,
    MinMaxScalerModel,
    OneHotEncoder,
    OneHotEncoderModel,
    PolynomialExpansion,
    QuantileDiscretizer,
    RegexTokenizer,
    RobustScaler,
    RobustScalerModel,
    SQLTransformer,
    StandardScaler,
    StandardScalerModel,
    StopWordsRemover,
    StringIndexer,
    StringIndexerModel,
    Tokenizer,
    VectorAssembler,
)

__all__ = [
    "COUNT_VECTORIZER_STATUS",
    "IDF",
    "IDF_STATUS",
    "QUANTILE_FAMILY_STATUS",
    "REGEX_TOKENIZER_GAPS_FALSE_STATUS",
    "Binarizer",
    "Bucketizer",
    "CountVectorizer",
    "CountVectorizerModel",
    "IDFModel",
    "Imputer",
    "ImputerModel",
    "IndexToString",
    "MaxAbsScaler",
    "MaxAbsScalerModel",
    "MinMaxScaler",
    "MinMaxScalerModel",
    "OneHotEncoder",
    "OneHotEncoderModel",
    "PolynomialExpansion",
    "QuantileDiscretizer",
    "RegexTokenizer",
    "RobustScaler",
    "RobustScalerModel",
    "SQLTransformer",
    "StandardScaler",
    "StandardScalerModel",
    "StopWordsRemover",
    "StringIndexer",
    "StringIndexerModel",
    "Tokenizer",
    "VectorAssembler",
]
